openapi: 3.0.1
info:
  contact:
    email: support@bitbucket.org
    name: Bitbucket Support
    url: https://support.atlassian.com/bitbucket-cloud/
  description: Code against the Bitbucket API to automate simple tasks, embed Bitbucket
    data into your own site, build mobile or desktop apps, or even add custom UI add-ons
    into Bitbucket itself using the Connect framework.
  termsOfService: https://www.atlassian.com/legal/customer-agreement
  title: Bitbucket API
  version: "2.0"
servers:
- url: https://api.bitbucket.org/2.0
tags:
- description: ""
  name: users
- description: ""
  name: teams
- description: ""
  name: repositories
- description: |-
    Browse the source code in the repository and
                                  create new commits by uploading.
  name: source
- description: ""
  name: refs
- description: ""
  name: commits
- description: ""
  name: pullrequests
- description: |-
    The issue resources provide functionality for getting information on
    issues in an issue tracker, creating new issues, updating them and deleting
    them.

    You can access public issues without authentication, but you can't gain access
    to private repositories' issues. By authenticating, you will get the ability
    to create issues, as well as access to updating data or deleting issues you
    have access to.
  name: issue_tracker
- description: ""
  name: wiki
- description: ""
  name: downloads
- description: ""
  name: snippets
- description: |
    Webhooks provide a way to configure Bitbucket Cloud to make requests to
    your server (or another external service) whenever certain events occur in
    Bitbucket Cloud.

    A webhook consists of:

    * A subject -- The resource that generates the events. Currently, this resource
      is the repository, user account, or team where you create the webhook.
    * One or more event -- The default event is a repository push, but you can
      select multiple events that can trigger the webhook.
    * A URL -- The endpoint where you want Bitbucket to send the event payloads
      when a matching event happens.

    There are two parts to getting a webhook to work: creating the webhook and
    triggering the webhook. After you create a webhook for an event, every time
    that event occurs, Bitbucket sends a payload request that describes the event
    to the specified URL. Thus, you can think of webhooks as a kind of
    notification system.

    Use webhooks to integrate applications with Bitbucket Cloud. The following
    use cases provides examples of when you would want to use webhooks:

    * Every time a user pushes commits in a repository, you may want to notify
      your CI server to start a build.
    * Every time a user pushes commits or creates a pull request, you may want to
      display a notification in your application.
  name: webhooks
- description: |
    Commit statuses provide a way to tag commits with meta data,
    like automated build results.
  name: commitstatuses
- description: |
    Repository owners and administrators can set branch management
    rules on a repository that control what can be pushed by whom.
    Through these rules, you can enforce a project or team
    workflow. For example, owners or administrators can:

    * Limit push powers
    * Prevent branch (bookmark) deletion
    * Prevent history re-writes (Git only)
  name: branchrestrictions
- description: |
    Bitbucket Cloud projects make it easier for teams to focus on
    a goal, product, or process by organizing their repositories.
  name: projects
- description: |
    Bitbucket Pipelines brings continuous delivery to Bitbucket
    Cloud, empowering teams with full branching to deployment
    visibility and faster feedback loops.
  name: pipelines
- description: |
    Teams are deploying code faster than ever, thanks to continuous
    delivery practices and tools like Bitbucket Pipelines. Bitbucket
    Deployments gives teams visibility into their deployment
    environments and helps teams to track how far changes have
    progressed in their deployment pipeline.
  name: deployments
paths:
  /repositories/{workspace}/{repo_slug}/branching-model:
    get:
      description: |-
        Return the branching model as applied to the repository. This view is
        read-only. The branching model settings can be changed using the
        [settings](branching-model/settings#get) API.

        The returned object:

        1. Always has a `development` property. `development.branch` contains
           the actual repository branch object that is considered to be the
           `development` branch. `development.branch` will not be present
           if it does not exist.
        2. Might have a `production` property. `production` will not
           be present when `production` is disabled.
           `production.branch` contains the actual branch object that is
           considered to be the `production` branch. `production.branch` will
           not be present if it does not exist.
        3. Always has a `branch_types` array which contains all enabled branch
           types.

        Example body:

        ```
        {
          "development": {
            "name": "master",
            "branch": {
              "type": "branch",
              "name": "master",
              "target": {
                "hash": "16dffcb0de1b22e249db6799532074cf32efe80f"
              }
            },
            "use_mainbranch": true
          },
          "production": {
            "name": "production",
            "branch": {
              "type": "branch",
              "name": "production",
              "target": {
                "hash": "16dffcb0de1b22e249db6799532074cf32efe80f"
              }
            },
            "use_mainbranch": false
          },
          "branch_types": [
            {
              "kind": "release",
              "prefix": "release/"
            },
            {
              "kind": "hotfix",
              "prefix": "hotfix/"
            },
            {
              "kind": "feature",
              "prefix": "feature/"
            },
            {
              "kind": "bugfix",
              "prefix": "bugfix/"
            }
          ],
          "type": "branching_model"
        }
        ```
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - branching_model
      x-tags:
      - tag: branching_model
  /repositories/{workspace}/{repo_slug}/commit/{commit}/properties/{app_key}/{property_name}:
    delete:
      description: Delete an application property value stored against a commit.
      operationId: deleteCommitHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    get:
      description: Retrieve an application property value stored against a commit.
      operationId: getCommitHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    put:
      description: Update an application property value stored against a commit.
      operationId: updateCommitHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
  /user:
    get:
      description: Returns the currently logged in user.
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /repositories/{workspace}/{repo_slug}/downloads/{filename}:
    delete:
      description: Deletes the specified download artifact from the repository.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - downloads
      x-tags:
      - tag: downloads
    get:
      description: |-
        Return a redirect to the contents of a download artifact.

        This endpoint returns the actual file contents and not the artifact's
        metadata.

            $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt
            Hello World
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - downloads
      x-tags:
      - tag: downloads
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes:
    get:
      description: |-
        Returns the list of all changes that have been made to the specified
        issue. Changes are returned in chronological order with the oldest
        change first.

        Each time an issue is edited in the UI or through the API, an immutable
        change record is created under the `/issues/123/changes` endpoint. It
        also has a comment associated with the change.

        Note that this operation is changing significantly, due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-the-issue-changes-api)
        for details.

        ```
        $ curl -s https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/issues/1/changes - | jq .

        {
          "pagelen": 20,
          "values": [
            {
              "changes": {
                "priority": {
                  "new": "trivial",
                  "old": "major"
                },
                "assignee": {
                  "new": "",
                  "old": "evzijst"
                },
                "assignee_account_id": {
                  "new": "",
                  "old": "557058:c0b72ad0-1cb5-4018-9cdc-0cde8492c443"
                },
                "kind": {
                  "new": "enhancement",
                  "old": "bug"
                }
              },
              "issue": {
                "type": "issue",
                "id": 1,
                "repository": {
                  "type": "repository",
                  "name": "dogslow",
                  "full_name": "evzijst/dogslow",
                  "uuid": "{988b17c6-1a47-4e70-84ee-854d5f012bf6}"
                },
                "title": "Updated title"
              },
              "created_on": "2018-03-03T00:35:28.353630+00:00",
              "user": {
                "username": "evzijst",
                "nickname": "evzijst",
                "display_name": "evzijst",
                "type": "user",
                "uuid": "{aaa7972b-38af-4fb1-802d-6e3854c95778}"
              },
              "message": {
                "raw": "Removed assignee, changed kind and priority.",
                "markup": "markdown",
                "html": "<p>Removed assignee, changed kind and priority.</p>",
                "type": "rendered"
              },
              "type": "issue_change",
              "id": 2
            }
          ],
          "page": 1
        }
        ```

        Changes support [filtering and sorting](../../../meta/filtering) that
        can be used to search for specific changes. For instance, to see
        when an issue transitioned to "resolved":

        ```
        $ curl -s https://api.bitbucket.org/2.0/repositories/site/master/issues/1/changes \
           -G --data-urlencode='q=changes.state.new = "resolved"'
        ```

        This resource is only available on repositories that have the issue
        tracker enabled.

        N.B.

        The `changes.assignee` and `changes.assignee_account_id` fields are not
        a `user` object. Instead, they contain the raw `username` and
        `account_id` of the user. This is to protect the integrity of the audit
        log even after a user account gets deleted.

        The `changes.assignee` field is deprecated will disappear in the
        future. Use `changes.assignee_account_id` instead.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    post:
      description: |-
        Makes a change to the specified issue.

        For example, to change an issue's state and assignee, create a new
        change object that modifies these fields:

        ```
        curl https://api.bitbucket.org/2.0/site/master/issues/1234/changes \
          -s -u evzijst -X POST -H "Content-Type: application/json" \
          -d '{
            "changes": {
              "assignee_account_id": {
                "new": "557058:c0b72ad0-1cb5-4018-9cdc-0cde8492c443"
              },
              "state": {
                "new": 'resolved"
              }
            }
            "message": {
              "raw": "This is now resolved."
            }
          }'
        ```

        The above example also includes a custom comment to go alongside the
        change. This comment will also be visible on the issue page in the UI.

        The fields of the `changes` object are strings, not objects. This
        allows for immutable change log records, even after user accounts,
        milestones, or other objects recorded in a change entry, get renamed or
        deleted.

        The `assignee_account_id` field stores the account id. When POSTing a
        new change and changing the assignee, the client should therefore use
        the user's account_id in the `changes.assignee_account_id.new` field.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorization.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/patch/{spec}:
    get:
      description: |-
        Produces a raw patch for a single commit (diffed against its first
        parent), or a patch-series for a revspec of 2 commits (e.g.
        `3a8b42..9ff173` where the first commit represents the source and the
        second commit the destination).

        In case of the latter (diffing a revspec), a patch series is returned
        for the commits on the source branch (`3a8b42` and its ancestors in
        our example). For Mercurial, a single patch is returned that combines
        the changes of all commits on the source branch.

        While similar to diffs, patches:

        * Have a commit header (username, commit message, etc)
        * Do not support the `path=foo/bar.py` query parameter

        The raw patch is returned as-is, in whatever encoding the files in the
        repository use. It is not decoded into unicode. As such, the
        content-type is `text/plain`.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /users/{username}/members:
    get:
      description: |-
        Returns all members of the specified team. Any member of any of the
        team's groups is considered a member of the team. This includes users
        in groups that may not actually have access to any of the team's
        repositories.

        This operation has been deprecated due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/)
        for details.
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}:
    delete:
      description: Deletes a specific pull request comment.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    get:
      description: Returns a specific pull request comment.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    put:
      description: Updates a specific pull request comment.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}:
    delete:
      description: Delete an application property value stored against a pull request.
      operationId: deletePullRequestHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    get:
      description: Retrieve an application property value stored against a pull request.
      operationId: getPullRequestHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    put:
      description: Update an application property value stored against a pull request.
      operationId: updatePullRequestHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
  /repositories/{workspace}/{repo_slug}/issues:
    get:
      description: Returns the issues in the issue tracker.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    post:
      description: |-
        Creates a new issue.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorization.

        The authenticated user is used for the issue's `reporter` field.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/downloads:
    get:
      description: Returns a list of download links associated with the repository.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - downloads
      x-tags:
      - tag: downloads
    post:
      description: |-
        Upload new download artifacts.

        To upload files, perform a `multipart/form-data` POST containing one
        or more `files` fields:

            $ echo Hello World > hello.txt
            $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt

        When a file is uploaded with the same name as an existing artifact,
        then the existing file will be replaced.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - downloads
      x-tags:
      - tag: downloads
  /repositories/{workspace}/{repo_slug}/deploy-keys:
    get:
      description: |-
        Returns all deploy-keys belonging to a repository.

        Example:
        ```
        $ curl -H "Authorization <auth header>" \
        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys

        Output:
        {
            "pagelen": 10,
            "values": [
                {
                    "id": 123,
                    "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5",
                    "label": "mykey",
                    "type": "deploy_key",
                    "created_on": "2018-08-15T23:50:59.993890+00:00",
                    "repository": {
                        "full_name": "mleu/test",
                        "name": "test",
                        "type": "repository",
                        "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
                    },
                    "last_used": null,
                    "comment": "mleu@C02W454JHTD8"
                }
            ],
            "page": 1,
            "size": 1
        }
        ```
      security:
      - oauth2:
        - repository
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - deploy
      x-tags:
      - tag: deploy
    post:
      description: |-
        Create a new deploy key in a repository.

        Example:
        ```
        $ curl -XPOST \
        -H "Authorization <auth header>" \
        -H "Content-type: application/json" \
        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys -d \
        '{
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5 mleu@C02W454JHTD8",
            "label": "mydeploykey"
        }'

        Output:
        {
            "id": 123,
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5",
            "label": "mydeploykey",
            "type": "deploy_key",
            "created_on": "2018-08-15T23:50:59.993890+00:00",
            "repository": {
                "full_name": "mleu/test",
                "name": "test",
                "type": "repository",
                "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
            },
            "last_used": null,
            "comment": "mleu@C02W454JHTD8"
        }
        ```
      security:
      - oauth2:
        - repository
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - deploy
      x-tags:
      - tag: deploy
  /repositories/{workspace}/{repo_slug}/commits:
    get:
      description: |-
        These are the repository's commits. They are paginated and returned
        in reverse chronological order, similar to the output of `git log` and
        `hg log`. Like these tools, the DAG can be filtered.

        ## GET /repositories/{workspace}/{repo_slug}/commits/

        Returns all commits in the repo in topological order (newest commit
        first). All branches and tags are included (similar to
        `git log --all` and `hg log`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/master

        Returns all commits on rev `master` (similar to `git log master`,
        `hg log master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/dev?exclude=master

        Returns all commits on ref `dev`, except those that are reachable on
        `master` (similar to `git log dev ^master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master

        Returns all commits in the repo that are not on master
        (similar to `git log --all ^master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar

        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or
        `fubar` (similar to `git log foo bar ^fu ^fubar`).

        An optional `path` parameter can be specified that will limit the
        results to commits that affect that path. `path` can either be a file
        or a directory. If a directory is specified, commits are returned that
        have modified any file in the directory tree rooted by `path`. It is
        important to note that if the `path` parameter is specified, the commits
        returned by this endpoint may no longer be a DAG, parent commits that
        do not modify the path will be omitted from the response.

        ## GET /repositories/{workspace}/{repo_slug}/commits/?path=README.md&include=foo&include=bar&exclude=master

        Returns all commits that are on refs `foo` or `bar`, but not on `master`
        that changed the file README.md.

        ## GET /repositories/{workspace}/{repo_slug}/commits/?path=src/&include=foo&include=bar&exclude=master

        Returns all commits that are on refs `foo` or `bar`, but not on `master`
        that changed to a file in any file in the directory src or its children.

        Because the response could include a very large number of commits, it
        is paginated. Follow the 'next' link in the response to navigate to the
        next page of commits. As with other paginated resources, do not
        construct your own links.

        When the include and exclude parameters are more than can fit in a
        query string, clients can use a `x-www-form-urlencoded` POST instead.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
    post:
      description: |-
        Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,
        except that POST allows clients to place the include and exclude
        parameters in the request body to avoid URL length issues.

        **Note that this resource does NOT support new commit creation.**
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /repositories/{workspace}/{repo_slug}/commit/{node}/approve:
    delete:
      description: |-
        Redact the authenticated user's approval of the specified commit.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
    post:
      description: |-
        Approve the specified commit as the authenticated user.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /teams/{username}/following:
    get:
      description: Returns the list of accounts this team is following.
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/branching-model/settings:
    get:
      description: |-
        Return the branching model configuration for a repository. The returned
        object:

        1. Always has a `development` property for the development branch.
        2. Always a `production` property for the production branch. The
           production branch can be disabled.
        3. The `branch_types` contains all the branch types.

        This is the raw configuration for the branching model. A client
        wishing to see the branching model with its actual current branches may
        find the [active model API](../branching-model#get) more useful.

        Example body:

        ```
        {
          "development": {
            "is_valid": true,
            "name": null,
            "use_mainbranch": true
          },
          "production": {
            "is_valid": true,
            "name": "production",
            "use_mainbranch": false,
            "enabled": false
          },
          "branch_types": [
            {
              "kind": "release",
              "enabled": true,
              "prefix": "release/"
            },
            {
              "kind": "hotfix",
              "enabled": true,
              "prefix": "hotfix/"
            },
            {
              "kind": "feature",
              "enabled": true,
              "prefix": "feature/"
            },
            {
              "kind": "bugfix",
              "enabled": false,
              "prefix": "bugfix/"
            }
          ],
          "type": "branching_model_settings"
        }
        ```
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branching_model
      x-tags:
      - tag: branching_model
    put:
      description: |-
        Update the branching model configuration for a repository.

        The `development` branch can be configured to a specific branch or to
        track the main branch. When set to a specific branch it must
        currently exist. Only the passed properties will be updated. The
        properties not passed will be left unchanged. A request without a
        `development` property will leave the development branch unchanged.

        It is possible for the `development` branch to be invalid. This
        happens when it points at a specific branch that has been
        deleted. This is indicated in the `is_valid` field for the branch. It is
        not possible to update the settings for `development` if that
        would leave the branch in an invalid state. Such a request will be
        rejected.

        The `production` branch can be a specific branch, the main
        branch or disabled. When set to a specific branch it must currently
        exist. The `enabled` property can be used to enable (`true`) or
        disable (`false`) it. Only the passed properties will be updated. The
        properties not passed will be left unchanged. A request without a
        `production` property will leave the production branch unchanged.

        It is possible for the `production` branch to be invalid. This
        happens when it points at a specific branch that has been
        deleted. This is indicated in the `is_valid` field for the branch. A
        request that would leave `production` enabled and invalid will be
        rejected. It is possible to update `production` and make it invalid if
        it would also be left disabled.

        The `branch_types` property contains the branch types to be updated.
        Only the branch types passed will be updated. All updates will be
        rejected if it would leave the branching model in an invalid state.
        For branch types this means that:

        1. The prefixes for all enabled branch types are valid. For example,
           it is not possible to use '*' inside a Git prefix.
        2. A prefix of an enabled branch type must not be a prefix of another
           enabled branch type. This is to ensure that a branch can be easily
           classified by its prefix unambiguously.

        It is possible to store an invalid prefix if that branch type would be
        left disabled. Only the passed properties will be updated. The
        properties not passed will be left unchanged. Each branch type must
        have a `kind` property to identify it.

        Example Body:

        ```
            {
              "development": {
                "use_mainbranch": true
              },
              "production": {
                "enabled": true,
                "use_mainbranch": false,
                "name": "production"
              },
              "branch_types": [
                {
                  "kind": "bugfix",
                  "enabled": true,
                  "prefix": "bugfix/"
                },
                {
                  "kind": "feature",
                  "enabled": true,
                  "prefix": "feature/"
                },
                {
                  "kind": "hotfix",
                  "prefix": "hotfix/"
                },
                {
                  "kind": "release",
                  "enabled": false
                }
              ]
            }
        ```
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branching_model
      x-tags:
      - tag: branching_model
  /teams/{username}/search/code:
    get:
      operationId: searchAccount
      summary: Search for code in the repositories of the specified team
      tags:
      - search
      x-tags:
      - tag: search
  /repositories/{workspace}/{repo_slug}/pipelines_config:
    get:
      description: Retrieve the repository pipelines configuration.
      operationId: getRepositoryPipelineConfig
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update the pipelines configuration for a repository.
      operationId: updateRepositoryPipelineConfig
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /teams/{username}/projects/:
    get:
      security:
      - oauth2:
        - project
      - basic: []
      - api_key: []
      tags:
      - projects
      x-tags:
      - tag: projects
    post:
      description: |-
        Creates a new project.

        Note that the avatar has to be embedded as either a data-url
        or a URL to an external image as shown in the examples below:

        ```
        $ body=$(cat << EOF
        {
            "name": "Mars Project",
            "key": "MARS",
            "description": "Software for colonizing mars.",
            "is_private": false
        }
        EOF
        )
        $ curl -H "Content-Type: application/json" \
               -X POST \
               -d "$body" \
               https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .
        {
          // Serialized project document
        }
        ```

        or even:

        ```
        $ body=$(cat << EOF
        {
            "name": "Mars Project",
            "key": "MARS",
            "description": "Software for colonizing mars.",
            "is_private": false
        }
        EOF
        )
        $ curl -H "Content-Type: application/json" \
               -X POST \
               -d "$body" \
               https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .
        {
          // Serialized project document
        }
        ```
      security:
      - oauth2:
        - project:write
      - basic: []
      - api_key: []
      tags:
      - projects
      x-tags:
      - tag: projects
  /repositories/{workspace}/{repo_slug}/hooks:
    get:
      description: Returns a paginated list of webhooks installed on this repository.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: webhooks
    post:
      description: |-
        Creates a new webhook on the specified repository.

        Example:

        ```
        $ curl -X POST -u credentials -H 'Content-Type: application/json'           https://api.bitbucket.org/2.0/repositories/username/slug/hooks           -d '
            {
              "description": "Webhook Description",
              "url": "https://example.com/",
              "active": true,
              "events": [
                "repo:push",
                "issue:created",
                "issue:updated"
              ]
            }'
        ```

        Note that this call requires the webhook scope, as well as any scope
        that applies to the events that the webhook subscribes to. In the
        example above that means: `webhook`, `repository` and `issue`.

        Also note that the `url` must properly resolve and cannot be an
        internal, non-routed address.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: webhooks
  /teams/{username}/permissions:
    get:
      description: "Returns an object for each team permission a user on the team\
        \ has.\n\nPermissions returned are effective permissions â\x80\x94 if a user\
        \ is a member of\nmultiple groups with distinct roles, only the highest level\
        \ is returned.\n\nPermissions can be:\n\n* `admin`\n* `collaborator`\n\nOnly\
        \ users with admin permission for the team may access this resource.\n\nExample:\n\
        \n```\n$ curl https://api.bitbucket.org/2.0/teams/atlassian_tutorial/permissions\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"permission\": \"\
        admin\",\n      \"type\": \"team_permission\",\n      \"user\": {\n      \
        \  \"type\": \"user\",\n        \"username\": \"evzijst\",\n        \"nickname\"\
        : \"evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"\
        uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"team\"\
        : {\n        \"username\": \"bitbucket\",\n        \"display_name\": \"Atlassian\
        \ Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    },\n    {\n      \"permission\": \"collaborator\",\n      \"\
        type\": \"team_permission\",\n      \"user\": {\n        \"type\": \"user\"\
        ,\n        \"username\": \"seanaty\",\n        \"nickname\": \"seanaty\",\n\
        \        \"display_name\": \"Sean Conaty\",\n        \"uuid\": \"{504c3b62-8120-4f0c-a7bc-87800b9d6f70}\"\
        \n      },\n      \"team\": {\n        \"username\": \"bitbucket\",\n    \
        \    \"display_name\": \"Atlassian Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    }\n  ],\n  \"page\": 1,\n  \"size\": 2\n}\n```\n\nResults may\
        \ be further [filtered or sorted](../../../meta/filtering) by\nteam, user,\
        \ or permission by adding the following query string\nparameters:\n\n* `q=user.username=\"\
        evzijst\"` or `q=permission=\"admin\"`\n* `sort=team.display_name`\n\nNote\
        \ that the query parameter values need to be URL escaped so that `=`\nwould\
        \ become `%3D`."
      security:
      - oauth2:
        - team
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /snippets/{username}/{encoded_id}/comments:
    get:
      description: |-
        Used to retrieve a paginated list of all comments for a specific
        snippet.

        This resource works identical to commit and pull request comments.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    post:
      description: |-
        Creates a new comment.

        The only required field in the body is `content.raw`.

        To create a threaded reply to an existing comment, include `parent.id`.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /users/{username}/search/code:
    get:
      operationId: searchAccount
      summary: Search for code in the repositories of the specified user
      tags:
      - search
      x-tags:
      - tag: search
  /teams/{username}/permissions/repositories:
    get:
      description: "Returns an object for each repository permission for all of a\n\
        teamâ\x80\x99s repositories.\n\nIf the username URL parameter refers to a\
        \ user account instead of\na team account, an object containing the repository\
        \ permissions\nof all the username's repositories will be returned.\n\nPermissions\
        \ returned are effective permissions â\x80\x94 the highest level of\npermission\
        \ the user has. This does not include public repositories that\nusers are\
        \ not granted any specific permission in, and does not\ndistinguish between\
        \ direct and indirect privileges.\n\nOnly users with admin permission for\
        \ the team may access this resource.\n\nPermissions can be:\n\n* `admin`\n\
        * `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/teams/atlassian_tutorial/permissions/repositories\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"type\": \"repository_permission\"\
        ,\n      \"user\": {\n        \"type\": \"user\",\n        \"username\": \"\
        evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"uuid\"\
        : \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"repository\"\
        : {\n        \"type\": \"repository\",\n        \"name\": \"geordi\",\n  \
        \      \"full_name\": \"bitbucket/geordi\",\n        \"uuid\": \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\
        \n      },\n      \"permission\": \"admin\"\n    },\n    {\n      \"type\"\
        : \"repository_permission\",\n      \"user\": {\n        \"type\": \"user\"\
        ,\n        \"username\": \"seanaty\",\n        \"display_name\": \"Sean Conaty\"\
        ,\n        \"uuid\": \"{504c3b62-8120-4f0c-a7bc-87800b9d6f70}\"\n      },\n\
        \      \"repository\": {\n        \"type\": \"repository\",\n        \"name\"\
        : \"geordi\",\n        \"full_name\": \"bitbucket/geordi\",\n        \"uuid\"\
        : \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\n      },\n      \"permission\"\
        : \"write\"\n    }\n  ],\n  \"page\": 1,\n  \"size\": 2\n}\n```\n\nResults\
        \ may be further [filtered or sorted](../../../../meta/filtering)\nby repository,\
        \ user, or permission by adding the following query string\nparameters:\n\n\
        * `q=repository.name=\"geordi\"` or `q=permission>\"read\"`\n* `sort=user.display_name`\n\
        \nNote that the query parameter values need to be URL escaped so that `=`\n\
        would become `%3D`."
      security:
      - oauth2:
        - team
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /repositories/{workspace}/{repo_slug}/refs/tags:
    get:
      description: |-
        Returns the tags in the repository.

        By default, results will be in the order the underlying source control system returns them and identical to
        the ordering one sees when running "$ hg tags" or "$ git tag --list". Note that this follows simple
        lexical ordering of the ref names.

        This can be undesirable as it does apply any natural sorting semantics, meaning for instance that tags are
        sorted ["v10", "v11", "v9"] instead of ["v9", "v10", "v11"].

        Sorting can be changed using the ?sort= query parameter. When using ?sort=name to explicitly sort on ref name,
        Bitbucket will apply natural sorting and interpret numerical values as numbers instead of strings.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
    post:
      description: |-
        Creates a new tag in the specified repository.

        The payload of the POST should consist of a JSON document that
        contains the name of the tag and the target hash.

        ```
        curl https://api.bitbucket.org/2.0/repositories/jdoe/myrepo/refs/tags \
        -s -u jdoe -X POST -H "Content-Type: application/json" \
        -d '{
            "name" : "new-tag-name",
            "target" : {
                "hash" : "a1b2c3d4e5f6"
            }
        }'
        ```

        This endpoint does support using short hash prefixes for the commit
        hash, but it may return a 400 response if the provided prefix is
        ambiguous. Using a full commit hash is the preferred approach.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
  /users/{username}/followers:
    get:
      description: |-
        Returns the list of accounts that are following this user.

        This operation has been deprecated due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/) for details.
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits:
    get:
      description: |-
        Returns a paginated list of the pull request's commits.

        These are the commits that are being merged into the destination
        branch when the pull requests gets accepted.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}:
    delete:
      description: Delete a schedule.
      operationId: deleteRepositoryPipelineSchedule
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve a schedule by its UUID.
      operationId: getRepositoryPipelineSchedule
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update a schedule.
      operationId: updateRepositoryPipelineSchedule
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /users/{username}/hooks/{uid}:
    delete:
      description: |-
        Deletes the specified webhook subscription from the given user
        account.

        Note that the username path parameter has been deprecated due to
        [privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).
        Use the account's UUID or account_id instead.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the given
        user account.

        Note that the username path parameter has been deprecated due to
        [privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).
        Use the account's UUID or account_id instead.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`

        Note that the username path parameter has been deprecated due to
        [privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).
        Use the account's UUID or account_id instead.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: webhooks
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      description: Returns the specified pull request.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    put:
      description: |-
        Mutates the specified pull request.

        This can be used to change the pull request's branches or description.

        Only open pull requests can be mutated.
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/vote:
    delete:
      description: Retract your vote.
      security:
      - oauth2:
        - issue:write
        - account:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    get:
      description: |-
        Check whether the authenticated user has voted for this issue.
        A 204 status code indicates that the user has voted, while a 404
        implies they haven't.
      security:
      - oauth2:
        - issue
        - account
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    put:
      description: |-
        Vote for this issue.

        To cast your vote, do an empty PUT. The 204 status code indicates that
        the operation was successful.
      security:
      - oauth2:
        - issue
        - account:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log:
    get:
      description: |-
        Retrieve the log file for a given step of a pipeline.

        This endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233) to deal with potentially very large log files.
      operationId: getPipelineStepLogForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /teams/{username}/hooks:
    get:
      description: Returns a paginated list of webhooks installed on this team.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - hasMore: "true"
        tag: teams
      - tag: webhooks
    post:
      description: |-
        Creates a new webhook on the specified team.

        Team webhooks are fired for events from all repositories belonging to
        that team account.

        Note that only admins can install webhooks on teams.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - hasMore: "true"
        tag: teams
      - tag: webhooks
  /users/{username}/following:
    get:
      description: |-
        Returns the list of accounts this user is following.

        This operation has been deprecated due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/) for details.
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /repositories/{workspace}/{repo_slug}/src:
    get:
      description: |-
        This endpoint redirects the client to the directory listing of the
        root directory on the main branch.

        This is equivalent to directly hitting
        [/2.0/repositories/{workspace}/{repo_slug}/src/{node}/{path}](src/%7Bnode%7D/%7Bpath%7D)
        without having to know the name or SHA1 of the repo's main branch.

        To create new commits, [POST to this endpoint](#post)
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - source
      x-tags:
      - hasMore: "true"
        tag: source
      - tag: repositories
    post:
      description: |-
        This endpoint is used to create new commits in the repository by
        uploading files.

        To add a new file to a repository:

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \
          -F /repo/path/to/image.png=@image.png
        ```

        This will create a new commit on top of the main branch, inheriting the
        contents of the main branch, but adding (or overwriting) the
        `image.png` file to the repository in the `/repo/path/to` directory.

        To create a commit that deletes files, use the `files` parameter:

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \
          -F files=/file/to/delete/1.txt \
          -F files=/file/to/delete/2.txt
        ```

        You can add/modify/delete multiple files in a request. Rename/move a
        file by deleting the old path and adding the content at the new path.

        This endpoint accepts `multipart/form-data` (as in the examples above),
        as well as `application/x-www-form-urlencoded`.

        ## multipart/form-data

        A `multipart/form-data` post contains a series of "form fields" that
        identify both the individual files that are being uploaded, as well as
        additional, optional meta data.

        Files are uploaded in file form fields (those that have a
        `Content-Disposition` parameter) whose field names point to the remote
        path in the repository where the file should be stored. Path field
        names are always interpreted to be absolute from the root of the
        repository, regardless whether the client uses a leading slash (as the
        above `curl` example did).

        File contents are treated as bytes and are not decoded as text.

        The commit message, as well as other non-file meta data for the
        request, is sent along as normal form field elements. Meta data fields
        share the same namespace as the file objects. For `multipart/form-data`
        bodies that should not lead to any ambiguity, as the
        `Content-Disposition` header will contain the `filename` parameter to
        distinguish between a file named "message" and the commit message field.

        ## application/x-www-form-urlencoded

        It is also possible to upload new files using a simple
        `application/x-www-form-urlencoded` POST. This can be convenient when
        uploading pure text files:

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src \
          --data-urlencode "/path/to/me.txt=Lorem ipsum." \
          --data-urlencode "message=Initial commit" \
          --data-urlencode "author=Erik van Zijst <erik.van.zijst@gmail.com>"
        ```

        There could be a field name clash if a client were to upload a file
        named "message", as this filename clashes with the meta data property
        for the commit message. To avoid this and to upload files whose names
        clash with the meta data properties, use a leading slash for the files,
        e.g. `curl --data-urlencode "/message=file contents"`.

        When an explicit slash is omitted for a file whose path matches that of
        a meta data parameter, then it is interpreted as meta data, not as a
        file.

        ## Executables and links

        While this API aims to facilitate the most common use cases, it is
        possible to perform some more advanced operations like creating a new
        symlink in the repository, or creating an executable file.

        Files can be supplied with a `x-attributes` value in the
        `Content-Disposition` header. For example, to upload an executable
        file, as well as create a symlink from `README.txt` to `README`:

        ```
        --===============1438169132528273974==
        Content-Type: text/plain; charset="us-ascii"
        MIME-Version: 1.0
        Content-Transfer-Encoding: 7bit
        Content-ID: "bin/shutdown.sh"
        Content-Disposition: attachment; filename="shutdown.sh"; x-attributes:"executable"

        #!/bin/sh
        halt

        --===============1438169132528273974==
        Content-Type: text/plain; charset="us-ascii"
        MIME-Version: 1.0
        Content-Transfer-Encoding: 7bit
        Content-ID: "/README.txt"
        Content-Disposition: attachment; filename="README.txt"; x-attributes:"link"

        README
        --===============1438169132528273974==--
        ```

        Links are files that contain the target path and have
        `x-attributes:"link"` set.

        When overwriting links with files, or vice versa, the newly uploaded
        file determines both the new contents, as well as the attributes. That
        means uploading a file without specifying `x-attributes="link"` will
        create a regular file, even if the parent commit hosted a symlink at
        the same path.

        The same applies to executables. When modifying an existing executable
        file, the form-data file element must include
        `x-attributes="executable"` in order to preserve the executable status
        of the file.

        Note that this API does not support the creation or manipulation of
        subrepos / submodules.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - source
      x-tags:
      - hasMore: "true"
        tag: source
      - tag: repositories
  /snippets/{username}/{encoded_id}/comments/{comment_id}:
    delete:
      description: |-
        Deletes a snippet comment.

        Comments can only be removed by their author.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    get:
      description: Returns the specific snippet comment.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    put:
      description: |-
        Updates a comment.

        Comments can only be updated by their author.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/environments/{environment_uuid}/changes/:
    post:
      description: Update an environment
      operationId: updateEnvironmentForRepository
      tags:
      - deployments
      x-tags:
      - tag: deployments
  /repositories/{workspace}/{repo_slug}/issues/import:
    get:
      description: |-
        When using GET, this endpoint reports the status of the current import task. Request example:

        ```
        $ curl -u <username> -X GET https://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/issues/import
        ```

        After the job has been scheduled, but before it starts executing, this endpoint's response is:

        ```
        < HTTP/1.1 202 Accepted
        {
            "type": "issue_job_status",
            "status": "PENDING",
            "phase": "Attachments",
            "total": 15,
            "count": 0,
            "percent": 0
        }
        ```

        Once it starts running, it is a 202 response with status STARTED and progress filled.

        After it is finished, it becomes a 200 response with status SUCCESS or FAILURE.
      security:
      - oauth2:
        - repository:admin
        - issue:write
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
    post:
      description: |-
        A POST request to this endpoint will import the zip file given by the archive parameter into the repository. All
        existing issues will be deleted and replaced by the contents of the imported zip file.

        Imports are done through a multipart/form-data POST. There is one valid and required form field, with the name
        "archive," which needs to be a file field:

        ```
        $ curl -u <username> -X POST -F archive=@/path/to/file.zip https://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/issues/import
        ```

        When the import job is accepted, here is example output:

        ```
        < HTTP/1.1 202 Accepted

        {
            "type": "issue_job_status",
            "status": "ACCEPTED",
            "phase": "Attachments",
            "total": 15,
            "count": 0,
            "percent": 0
        }
        ```
      security:
      - oauth2:
        - repository:admin
        - issue:write
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /teams/{username}/repositories:
    get:
      description: |-
        All repositories owned by a user/team. This includes private
        repositories, but filtered down to the ones that the calling user has
        access to.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: teams
  /snippets/{username}/{encoded_id}/{node_id}/files/{path}:
    get:
      description: |-
        Retrieves the raw contents of a specific file in the snippet. The
        `Content-Disposition` header will be "attachment" to avoid issues with
        malevolent executable files.

        The file's mime type is derived from its filename and returned in the
        `Content-Type` header.

        Note that for text files, no character encoding is included as part of
        the content type.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /user/permissions/repositories:
    get:
      description: "Returns an object for each repository the caller has explicit\
        \ access\nto and their effective permission â\x80\x94 the highest level of\
        \ permission the\ncaller has. This does not return public repositories that\
        \ the user was\nnot granted any specific permission in, and does not distinguish\
        \ between\ndirect and indirect privileges.\n\nPermissions can be:\n\n* `admin`\n\
        * `write`\n* `read`\n\nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/repositories\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"type\": \"repository_permission\"\
        ,\n      \"user\": {\n        \"type\": \"user\",\n        \"username\": \"\
        evzijst\",\n        \"nickname\": \"evzijst\",\n        \"display_name\":\
        \ \"Erik van Zijst\",\n        \"uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\"\
        \n      },\n      \"repository\": {\n        \"type\": \"repository\",\n \
        \       \"name\": \"geordi\",\n        \"full_name\": \"bitbucket/geordi\"\
        ,\n        \"uuid\": \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\n      },\n\
        \      \"permission\": \"admin\"\n    }\n  ],\n  \"page\": 1,\n  \"size\"\
        : 1\n}\n```\n\nResults may be further [filtered or sorted](../../../meta/filtering)\
        \ by\nrepository or permission by adding the following query string\nparameters:\n\
        \n* `q=repository.name=\"geordi\"` or `q=permission>\"read\"`\n* `sort=repository.name`\n\
        \nNote that the query parameter values need to be URL escaped so that `=`\n\
        would become `%3D`."
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/hooks/{uid}:
    delete:
      description: |-
        Deletes the specified webhook subscription from the given
        repository.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the specified
        repository.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: webhooks
  /repositories/{workspace}/{repo_slug}/environments/:
    get:
      description: Find environments
      operationId: getEnvironmentsForRepository
      tags:
      - deployments
      x-tags:
      - tag: deployments
    post:
      description: Create an environment.
      operationId: createEnvironment
      tags:
      - deployments
      x-tags:
      - tag: deployments
  /teams/{username}/pipelines_config/variables/{variable_uuid}:
    delete:
      description: Delete a team level variable.
      operationId: deletePipelineVariableForTeam
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve a team level variable.
      operationId: getPipelineVariableForTeam
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update a team level variable.
      operationId: updatePipelineVariableForTeam
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/default-reviewers:
    get:
      description: |-
        Returns the repository's default reviewers.

        These are the users that are automatically added as reviewers on every
        new pull request that is created.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve:
    delete:
      description: |-
        Redact the authenticated user's approval of the specified pull
        request.
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    post:
      description: Approve the specified pull request as the authenticated user.
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/milestones/{milestone_id}:
    get:
      description: Returns the specified issue tracker milestone object.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/milestones:
    get:
      description: |-
        Returns the milestones that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/issues/export:
    post:
      description: |-
        A POST request to this endpoint initiates a new background celery task that archives the repo's issues.

        For example, you can run:

        curl -u <username> -X POST http://api.bitbucket.org/2.0/repositories/<owner_username>/<repo_slug>/
        issues/export

        When the job has been accepted, it will return a 202 (Accepted) along with a unique url to this job in the
        'Location' response header. This url is the endpoint for where the user can obtain their zip files."
      security:
      - oauth2:
        - repository:admin
        - issue
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /user/emails:
    get:
      description: |-
        Returns all the authenticated user's email addresses. Both
        confirmed and unconfirmed.
      security:
      - oauth2:
        - email
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /repositories/{workspace}/{repo_slug}/refs/branches:
    get:
      description: |-
        Returns a list of all open branches within the specified repository.
        Results will be in the order the source control manager returns them.

        ```
        $ curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/mercurial/refs/branches | jq .
        {
          "pagelen": 10,
          "values": [
            {
              "heads": [
                {
                  "hash": "f1a0933ce59e809f190602655e22ae6ec107c397",
                  "type": "commit"
                }
              ],
              "type": "named_branch",
              "name": "default",
              "target": {
                "hash": "f1a0933ce59e809f190602655e22ae6ec107c397",
                "repository": {
                  "type": "repository",
                  "name": "mercurial",
                  "full_name": "seanfarley/mercurial",
                  "uuid": "{73dcbd61-e506-4fc1-9ecd-31be2b6d6031}"
                },
                "author": {
                  "raw": "Martin von Zweigbergk <martinvonz@google.com>",
                  "type": "author",
                  "user": {
                    "username": "martinvonz",
                    "nickname": "martinvonz",
                    "display_name": "Martin von Zweigbergk",
                    "type": "user",
                    "uuid": "{fdb0e657-3ade-4fad-a136-95f1ffe4a5ac}"
                  }
                },
                "parents": [
                  {
                    "hash": "5523aabb85c30ebc2b8e29aadcaf5e13fa92b375",
                    "type": "commit"
                  }
                ],
                "date": "2018-02-01T18:44:49+00:00",
                "message": "config: replace a for-else by any()",
                "type": "commit"
              }
            },
            {
              "heads": [
                {
                  "hash": "1d60ad093792706e1dc7a52b20942593f2c19655",
                  "type": "commit"
                }
              ],
              "type": "named_branch",
              "name": "stable",
              "target": {
                "hash": "1d60ad093792706e1dc7a52b20942593f2c19655",
                "repository": {
                  "type": "repository",
                  "name": "mercurial",
                  "full_name": "seanfarley/mercurial",
                  "uuid": "{73dcbd61-e506-4fc1-9ecd-31be2b6d6031}"
                },
                "author": {
                  "raw": "Augie Fackler <raf@durin42.com>",
                  "type": "author",
                  "user": {
                    "username": "durin42",
                    "nickname": "durin42",
                    "display_name": "Augie Fackler",
                    "type": "user",
                    "uuid": "{e07dc61f-bb05-4218-b43a-d991f26be65a}"
                  }
                },
                "parents": [
                  {
                    "hash": "56a0da11bde519d79168e890df4bcf0da62f0a7b",
                    "type": "commit"
                  }
                ],
                "date": "2018-02-01T19:13:41+00:00",
                "message": "Added signature for changeset d334afc585e2",
                "type": "commit"
              }
            }
          ],
          "page": 1,
          "size": 2
        }
        ```

        Branches support [filtering and sorting](../../../../../meta/filtering)
        that can be used to search for specific branches. For instance, to find
        all branches that have "stab" in their name:

        ```
        curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/mercurial/refs/branches -G --data-urlencode 'q=name ~ "stab"'
        ```

        By default, results will be in the order the underlying source control system returns them and identical to
        the ordering one sees when running "$ hg branches" or "$ git branch --list". Note that this follows simple
        lexical ordering of the ref names.

        This can be undesirable as it does apply any natural sorting semantics, meaning for instance that tags are
        sorted ["v10", "v11", "v9"] instead of ["v9", "v10", "v11"].

        Sorting can be changed using the ?q= query parameter. When using ?q=name to explicitly sort on ref name,
        Bitbucket will apply natural sorting and interpret numerical values as numbers instead of strings.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
    post:
      description: |-
        Creates a new branch in the specified repository.

        The payload of the POST should consist of a JSON document that
        contains the name of the tag and the target hash.

        ```
        curl https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/branches \
        -s -u seanfarley -X POST -H "Content-Type: application/json" \
        -d '{
            "name" : "smf/create-feature",
            "target" : {
                "hash" : "default"
            }
        }'
        ```

        This call requires authentication. Private repositories require the
        caller to authenticate with an account that has appropriate
        authorization.

        For Git, the branch name should not include any prefixes (e.g.
        refs/heads). This endpoint does support using short hash prefixes for
        the commit hash, but it may return a 400 response if the provided
        prefix is ambiguous. Using a full commit hash is the preferred
        approach.

        For Mercurial, the authenticated user making this call is the author of
        the new branch commit and the date is current datetime of the call.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
  /addon/linkers/{linker_key}:
    get:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /snippets/{username}/{encoded_id}/watchers:
    get:
      deprecated: true
      description: Returns a paginated list of all users watching a specific snippet.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/versions/{version_id}:
    get:
      description: Returns the specified issue tracker version object.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments/{comment_id}:
    delete:
      description: Deletes the specified comment.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    get:
      description: Returns the specified issue comment object.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    put:
      description: |-
        Updates the content of the specified issue comment. Note that only
        the `content.raw` field can be modified.

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/5728901 \
          -X PUT -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}'
        ```
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments:
    get:
      description: |-
        Returns all attachments for this issue.

        This returns the files' meta data. This does not return the files'
        actual contents.

        The files are always ordered by their upload date.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    post:
      description: |-
        Upload new issue attachments.

        To upload files, perform a `multipart/form-data` POST containing one
        or more file fields.

        When a file is uploaded with the same name as an existing attachment,
        then the existing file will be replaced.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /snippets/{username}/{encoded_id}/{revision}/patch:
    get:
      description: |-
        Returns the patch of the specified commit against its first
        parent.

        Note that this resource is different in functionality from the `diff`
        resource.

        The differences between a diff and a patch are:

        * patches have a commit header with the username, message, etc
        * diffs support the optional `path=foo/bar.py` query param to filter the
          diff to just that one file diff (not supported for patches)
        * for a merge, the diff will show the diff between the merge commit and
          its first parent (identical to how PRs work), while patch returns a
          response containing separate patches for each commit on the second
          parent's ancestry, up to the oldest common ancestor (identical to
          its reachability).

        Note that the character encoding of the contents of the patch is
        unspecified as Git and Mercurial do not track this, making it hard for
        Bitbucket to reliably determine this.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/refs/tags/{name}:
    delete:
      description: |-
        Delete a tag in the specified repository.

        For Git, the tag name should not include any prefixes (e.g. refs/tags).
        For Mercurial, this adds a commit to the main branch that removes the
        specified tag.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
    get:
      description: |-
        Returns the specified tag.

        ```
        $ curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8 -G | jq .
        {
          "name": "3.8",
          "tagger": {
            "raw": "Matt Mackall <mpm@selenic.com>",
            "type": "author",
            "user": {
              "username": "mpmselenic",
              "nickname": "mpmselenic",
              "display_name": "Matt Mackall",
              "type": "user",
              "uuid": "{a4934530-db4c-419c-a478-9ab4964c2ee7}"
            }
          },
          "date": "2016-05-01T18:52:25+00:00",
          "message": "Added tag 3.8 for changeset f85de28eae32",
          "type": "tag",
          "target": {
            "hash": "f85de28eae32e7d3064b1a1321309071bbaaa069",
            "repository": {
              "type": "repository",
              "name": "hg",
              "full_name": "seanfarley/hg",
              "uuid": "{c75687fb-e99d-4579-9087-190dbd406d30}"
            },
            "author": {
              "raw": "Sean Farley <sean@farley.io>",
              "type": "author",
              "user": {
                "username": "seanfarley",
                "nickname": "seanfarley",
                "display_name": "Sean Farley",
                "type": "user",
                "uuid": "{a295f8a8-5876-4d43-89b5-3ad8c6c3c51d}"
              }
            },
            "parents": [
              {
                "hash": "9a98d0e5b07fc60887f9d3d34d9ac7d536f470d2",
                "type": "commit"
              }
            ],
            "date": "2016-05-01T04:21:17+00:00",
            "message": "debian: alphabetize build deps",
            "type": "commit"
          }
        }
        ```
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}:
    get:
      description: Retrieve a given step of a pipeline.
      operationId: getPipelineStepForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}:
    delete:
      description: |-
        Deletes the repository. This is an irreversible operation.

        This does not affect its forks.
      security:
      - oauth2:
        - repository:delete
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
    get:
      description: Returns the object describing this repository.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
    post:
      description: |-
        Creates a new repository.

        Note: In order to set the project for the newly created repository,
        pass in either the project key or the project UUID as part of the
        request body as shown in the examples below:

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "MARS"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        or

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "{ba516952-992a-4c2d-acbd-17d502922f96}"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        The project must only be assigned for repositories belonging to a team.
        If the repository owner is a team and the project is not provided, the
        repository is automatically assigned to the oldest project in the team.

        Note: In the examples above, the username `teamsinspace`,
        and/or the repository name `hablanding` can be replaced by UUIDs.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
    put:
      description: |-
        Since this endpoint can be used to both update and to create a
        repository, the request body depends on the intent.

        ### Creation

        See the POST documentation for the repository endpoint for an example
        of the request body.

        ### Update

        Note: Changing the `name` of the repository will cause the location to
        be changed. This is because the URL of the repo is derived from the
        name (a process called slugification). In such a scenario, it is
        possible for the request to fail if the newly created slug conflicts
        with an existing repository's slug. But if there is no conflict,
        the new location will be returned in the `Location` header of the
        response.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /addon/linkers/{linker_key}/values:
    delete:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
    get:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
    post:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
    put:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline:
    post:
      description: Signal the stop of a pipeline and all of its steps that not have
        completed yet.
      operationId: stopPipeline
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/pullrequests:
    get:
      description: |-
        Returns all pull requests on the specified repository.

        By default only open pull requests are returned. This can be controlled
        using the `state` query parameter. To retrieve pull requests that are
        in one of multiple states, repeat the `state` parameter for each
        individual state.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../meta/filtering) for more details.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    post:
      description: |-
        Creates a new pull request where the destination repository is
        this repository and the author is the authenticated user.

        The minimum required fields to create a pull request are `title` and
        `source`, specified by a branch name.

        ```
        curl https://api.bitbucket.org/2.0/repositories/my-username/my-repository/pullrequests \
            -u my-username:my-password \
            --request POST \
            --header 'Content-Type: application/json' \
            --data '{
                "title": "My Title",
                "source": {
                    "branch": {
                        "name": "staging"
                    }
                }
            }'
        ```

        If the pull request's `destination` is not specified, it will default
        to the `repository.mainbranch`. To open a pull request to a
        different branch, say from a feature branch to a staging branch,
        specify a `destination` (same format as the `source`):

        ```
        {
            "title": "My Title",
            "source": {
                "branch": {
                    "name": "my-feature-branch"
                }
            },
            "destination": {
                "branch": {
                    "name": "staging"
                }
            }
        }
        ```

        Reviewers can be specified by adding an array of user objects as the
        `reviewers` property.

        ```
        {
            "title": "My Title",
            "source": {
                "branch": {
                    "name": "my-feature-branch"
                }
            },
            "reviewers": [
                {
                    "uuid": "{504c3b62-8120-4f0c-a7bc-87800b9d6f70}"
                }
            ]
        }
        ```

        Other fields:

        * `description` - a string
        * `close_source_branch` - boolean that specifies if the source branch should be closed upon merging
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /addon:
    delete:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
    put:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/key_pair:
    delete:
      description: Delete the repository SSH key pair.
      operationId: deleteRepositoryPipelineKeyPair
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve the repository SSH key pair excluding the SSH private
        key. The private key is a write only field and will never be exposed in the
        logs or the REST API.
      operationId: getRepositoryPipelineSshKeyPair
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Create or update the repository SSH key pair. The private key will
        be set as a default SSH identity in your build container.
      operationId: updateRepositoryPipelineKeyPair
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/pipelines_config/variables/:
    get:
      description: Find repository level variables.
      operationId: getRepositoryPipelineVariables
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: Create a repository level variable.
      operationId: createRepositoryPipelineVariable
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /teams/{username}/permissions/repositories/{repo_slug}:
    get:
      description: "Returns an object for each repository permission of a given repository.\n\
        \nIf the username URL parameter refers to a user account instead of\na team\
        \ account, an object containing the repository permissions\nof the username's\
        \ repository will be returned.\n\nPermissions returned are effective permissions\
        \ â\x80\x94 the highest level of\npermission the user has. This does not include\
        \ public repositories that\nusers are not granted any specific permission\
        \ in, and does not\ndistinguish between direct and indirect privileges.\n\n\
        Only users with admin permission for the repository may access this resource.\n\
        \nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n\nExample:\n\n```\n\
        $ curl https://api.bitbucket.org/2.0/teams/atlassian_tutorial/permissions/repositories/geordi\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"type\": \"repository_permission\"\
        ,\n      \"user\": {\n        \"type\": \"user\",\n        \"username\": \"\
        evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"uuid\"\
        : \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"repository\"\
        : {\n        \"type\": \"repository\",\n        \"name\": \"geordi\",\n  \
        \      \"full_name\": \"bitbucket/geordi\",\n        \"uuid\": \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\
        \n      },\n      \"permission\": \"admin\"\n    },\n    {\n      \"type\"\
        : \"repository_permission\",\n      \"user\": {\n        \"type\": \"user\"\
        ,\n        \"username\": \"seanaty\",\n        \"display_name\": \"Sean Conaty\"\
        ,\n        \"uuid\": \"{504c3b62-8120-4f0c-a7bc-87800b9d6f70}\"\n      },\n\
        \      \"repository\": {\n        \"type\": \"repository\",\n        \"name\"\
        : \"geordi\",\n        \"full_name\": \"bitbucket/geordi\",\n        \"uuid\"\
        : \"{85d08b4e-571d-44e9-a507-fa476535aa98}\"\n      },\n      \"permission\"\
        : \"write\"\n    }\n  ],\n  \"page\": 1,\n  \"size\": 2\n}\n```\n\nResults\
        \ may be further [filtered or sorted](../../../../meta/filtering)\nby user,\
        \ or permission by adding the following query string parameters:\n\n* `q=permission>\"\
        read\"`\n* `sort=user.display_name`\n\nNote that the query parameter values\
        \ need to be URL escaped so that `=`\nwould become `%3D`."
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /repositories/{workspace}/{repo_slug}/branch-restrictions/{id}:
    delete:
      description: Deletes an existing branch restriction rule.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branchrestrictions
      x-tags:
      - tag: branchrestrictions
    get:
      description: Returns a specific branch restriction rule.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branchrestrictions
      x-tags:
      - tag: branchrestrictions
    put:
      description: |-
        Updates an existing branch restriction rule.

        Fields not present in the request body are ignored.

        See [`POST`](../branch-restrictions#post) for details.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branchrestrictions
      x-tags:
      - tag: branchrestrictions
  /teams/{username}/pipelines_config/variables/:
    get:
      description: Find account level variables.
      operationId: getPipelineVariablesForTeam
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: Create an account level variable.
      operationId: createPipelineVariableForTeam
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /users/{username}/ssh-keys/:
    delete:
      description: |-
        Deletes a specific SSH public key from a user's account

        Example:
        ```
        $ curl -X DELETE https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}
        ```
      security:
      - oauth2:
        - account:write
      - basic: []
      - api_key: []
      tags:
      - ssh
      x-tags:
      - tag: ssh
    get:
      description: |-
        Returns a specific SSH public key belonging to a user.

        Example:
        ```
        $ curl https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{fbe4bbab-f6f7-4dde-956b-5c58323c54b3}

        {
            "comment": "user@myhost",
            "created_on": "2018-03-14T13:17:05.196003+00:00",
            "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY",
            "label": "",
            "last_used": "2018-03-20T13:18:05.196003+00:00",
            "owner": {
                "display_name": "Mark Adams",
                "type": "user",
                "username": "markadams-atl",
                "nickname": "markadams-atl",
                "uuid": "{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}"
            },
            "type": "ssh_key",
            "uuid": "{b15b6026-9c02-4626-b4ad-b905f99f763a}"
        }
        ```
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - ssh
      x-tags:
      - tag: ssh
    put:
      description: |-
        Updates a specific SSH public key on a user's account

        Note: Only the 'comment' field can be updated using this API. To modify the key or comment values, you must delete and add the key again.

        Example:
        ```
        $ curl -X PUT -H "Content-Type: application/json" -d '{"label": "Work key"}' https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys/{b15b6026-9c02-4626-b4ad-b905f99f763a}

        {
            "comment": "",
            "created_on": "2018-03-14T13:17:05.196003+00:00",
            "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY",
            "label": "Work key",
            "last_used": "2018-03-20T13:18:05.196003+00:00",
            "owner": {
                "display_name": "Mark Adams",
                "type": "user",
                "username": "markadams-atl",
                "nickname": "markadams-atl",
                "uuid": "{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}"
            },
            "type": "ssh_key",
            "uuid": "{b15b6026-9c02-4626-b4ad-b905f99f763a}"
        }
        ```
      security:
      - oauth2:
        - account:write
      - basic: []
      - api_key: []
      tags:
      - ssh
      x-tags:
      - tag: ssh
  /repositories/{workspace}/{repo_slug}/commit/{node}/comments/{comment_id}:
    get:
      description: Returns the specified commit comment.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /repositories/{workspace}/{repo_slug}/forks:
    get:
      description: |-
        Returns a paginated list of all the forks of the specified
        repository.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
    post:
      description: |-
        Creates a new fork of the specified repository.

        By default, forks are created under the authenticated user's account
        with the same name and slug of the original repository.

        ```
        $ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/forks

        {
          "scm": "git",
          "full_name": "jdoe/dogslow",
          "parent": {
            "full_name": "evzijst/dogslow",
            ...
          },
          ...
        }
        ```

        If you already have a repo with that name, then a 400 is returned and
        you'll need to specify a custom name for the new fork:

        ```
        $ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/forks \
          -H 'Content-Type: application/json' -d '{
            "name": "dogslow_fork"
        }'
        ```

        When you specify a value for `name`, it will also affect the `slug`.
        The `slug` is reflected in the repository URL of the new fork. It is
        derived from `name` by substituting non-ASCII characters, removes
        whitespace, and changes characters to lower case. For example,
        `My repo` would turn into `my_repo`.

        ## Forking a repository into a team account

        To create a fork into a team account, specify the new owner's account
        explicitly as part of the request body. This prevents forked
        repositories from being owned by the authenticated user submitting the
        ```
        $ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/atlassian/bbql/forks \
          -H 'Content-Type: application/json' -d '{
            "name": "bbql_fork",
            "owner": {
              "username": "atlassian"
            }
        }'
        ```

        To fork a repository into the same team, also specify a new `name`.

        You need contributor access to create new forks within a team account.


        ## Change the properties of a new fork

        By default the fork inherits most of its properties from the parent.
        However, since the optional POST body document follows the normal
        `repository` JSON schema and you can override the new fork's
        properties.

        Properties that can be overridden include:

        * description
        * fork_policy
        * language
        * mainbranch
        * is_private (note that a private repo's fork_policy might prohibit
          the creation of public forks, in which `is_private=False` would fail)
        * has_issues (to initialize or disable the new repo's issue tracker --
          note that the actual contents of the parent repository's issue
          tracker are not copied during forking)
        * has_wiki (to initialize or disable the new repo's wiki --
          note that the actual contents of the parent repository's wiki are not
          copied during forking)
        * project (only teams have projects and when forking into a private
          project, the fork's `is_private` must be `true`)

        Properties that cannot be modified include:

        * scm
        * parent
        * full_name
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /snippets/{username}/{encoded_id}:
    delete:
      description: Deletes a snippet and returns an empty response.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    get:
      description: |-
        Retrieves a single snippet.

        Snippets support multiple content types:

        * application/json
        * multipart/related
        * multipart/form-data


        application/json
        ----------------

        The default content type of the response is `application/json`.
        Since JSON is always `utf-8`, it cannot reliably contain file contents
        for files that are not text. Therefore, JSON snippet documents only
        contain the filename and links to the file contents.

        This means that in order to retrieve all parts of a snippet, N+1
        requests need to be made (where N is the number of files in the
        snippet).


        multipart/related
        -----------------

        To retrieve an entire snippet in a single response, use the
        `Accept: multipart/related` HTTP request header.

            $ curl -H "Accept: multipart/related" https://api.bitbucket.org/2.0/snippets/evzijst/1

        Response:

            HTTP/1.1 200 OK
            Content-Length: 2214
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "id": kypj,
              "title": "My snippet",
              "created_on": "2014-12-29T22:22:04.790331+00:00",
              "updated_on": "2014-12-29T22:22:04.790331+00:00",
              "is_private": false,
              "files": {
                "foo.txt": {
                },
                "image.png": {
                }
              ],
              "owner": {
                "username": "evzijst",
                "nickname": "evzijst",
                "display_name": "Erik van Zijst",
                "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}"
              },
              "creator": {
                "username": "evzijst",
                "nickname": "evzijst",
                "display_name": "Erik van Zijst",
                "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}"
              }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            foo

            --===============1438169132528273974==
            Content-Type: image/png
            MIME-Version: 1.0
            Content-Transfer-Encoding: base64
            Content-ID: "image.png"
            Content-Disposition: attachment; filename="image.png"

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            --===============1438169132528273974==--

        multipart/form-data
        -------------------

        As with creating new snippets, `multipart/form-data` can be used as an
        alternative to `multipart/related`. However, the inherently flat
        structure of form-data means that only basic, root-level properties
        can be returned, while nested elements like `links` are omitted:

            $ curl -H "Accept: multipart/form-data" https://api.bitbucket.org/2.0/snippets/evzijst/kypj

        Response:

            HTTP/1.1 200 OK
            Content-Length: 951
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"
            Content-Type: text/plain; charset="utf-8"

            My snippet
            ------------------------------63a4b224c59f--
            Content-Disposition: attachment; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: attachment; name="file"; filename="image.png"
            Content-Transfer-Encoding: base64
            Content-Type: application/octet-stream

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            ------------------------------5957323a6b76--
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    put:
      description: |-
        Used to update a snippet. Use this to add and delete files and to
        change a snippet's title.

        To update a snippet, one can either PUT a full snapshot, or only the
        parts that need to be changed.

        The contract for PUT on this API is that properties missing from the
        request remain untouched so that snippets can be efficiently
        manipulated with differential payloads.

        To delete a property (e.g. the title, or a file), include its name in
        the request, but omit its value (use `null`).

        As in Git, explicit renaming of files is not supported. Instead, to
        rename a file, delete it and add it again under another name. This can
        be done atomically in a single request. Rename detection is left to
        the SCM.

        PUT supports three different content types for both request and
        response bodies:

        * `application/json`
        * `multipart/related`
        * `multipart/form-data`

        The content type used for the request body can be different than that
        used for the response. Content types are specified using standard HTTP
        headers.

        Use the `Content-Type` and `Accept` headers to select the desired
        request and response format.


        application/json
        ----------------

        As with creation and retrieval, the content type determines what
        properties can be manipulated. `application/json` does not support
        file contents and is therefore limited to a snippet's meta data.

        To update the title, without changing any of its files:

            $ curl -X POST -H "Content-Type: application/json" https://api.bitbucket.org/2.0/snippets/evzijst/kypj             -d '{"title": "Updated title"}'


        To delete the title:

            $ curl -X POST -H "Content-Type: application/json" https://api.bitbucket.org/2.0/snippets/evzijst/kypj             -d '{"title": null}'

        Not all parts of a snippet can be manipulated. The owner and creator
        for instance are immutable.


        multipart/related
        -----------------

        `multipart/related` can be used to manipulate all of a snippet's
        properties. The body is identical to a POST. properties omitted from
        the request are left unchanged. Since the `start` part contains JSON,
        the mechanism for manipulating the snippet's meta data is identical
        to `application/json` requests.

        To update one of a snippet's file contents, while also changing its
        title:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 288
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "title": "My updated snippet",
              "files": {
                  "foo.txt": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            Updated file contents.

            --===============1438169132528273974==--

        Here only the parts that are changed are included in the body. The
        other files remain untouched.

        Note the use of the `files` list in the JSON part. This list contains
        the files that are being manipulated. This list should have
        corresponding multiparts in the request that contain the new contents
        of these files.

        If a filename in the `files` list does not have a corresponding part,
        it will be deleted from the snippet, as shown below:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 188
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "files": {
                "image.png": {}
              }
            }

            --===============1438169132528273974==--

        To simulate a rename, delete a file and add the same file under
        another name:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 212
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
                "files": {
                  "foo.txt": {},
                  "bar.txt": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "bar.txt"
            Content-Disposition: attachment; filename="bar.txt"

            foo

            --===============1438169132528273974==--


        multipart/form-data
        -----------------

        Again, one can also use `multipart/form-data` to manipulate file
        contents and meta data atomically.

            $ curl -X PUT http://localhost:12345/2.0/snippets/evzijst/kypj             -F title="My updated snippet" -F file=@foo.txt

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 351
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"

            My updated snippet
            ------------------------------63a4b224c59f

        To delete a file, omit its contents while including its name in the
        `files` field:

            $ curl -X PUT https://api.bitbucket.org/2.0/snippets/evzijst/kypj -F files=image.png

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 149
            Content-Type: multipart/form-data; boundary=----------------------------ef8871065a86

            ------------------------------ef8871065a86
            Content-Disposition: form-data; name="files"

            image.png
            ------------------------------ef8871065a86--

        The explicit use of the `files` element in `multipart/related` and
        `multipart/form-data` is only required when deleting files.
        The default mode of operation is for file parts to be processed,
        regardless of whether or not they are listed in `files`, as a
        convenience to the client.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/diff/{spec}:
    get:
      description: |-
        Produces a raw, git-style diff for either a single commit (diffed
        against its first parent), or a revspec of 2 commits (e.g.
        `3a8b42..9ff173` where the first commit represents the source and the
        second commit the destination).

        In case of the latter (diffing a revspec), a 3-way diff, or merge diff,
        is computed. This shows the changes introduced by the left branch
        (`3a8b42` in our example) as compared againt the right branch
        (`9ff173`).

        This is equivalent to merging the left branch into the right branch and
        then computing the diff of the merge commit against its first parent
        (the right branch). This follows the same behavior as pull requests
        that also show this style of 3-way, or merge diff.

        While similar to patches, diffs:

        * Don't have a commit header (username, commit message, etc)
        * Support the optional `path=foo/bar.py` query param to filter
          the diff to just that one file diff

        The raw diff is returned as-is, in whatever encoding the files in the
        repository use. It is not decoded into unicode. As such, the
        content-type is `text/plain`.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /repositories/{workspace}/{repo_slug}/deployments/:
    get:
      description: Find deployments
      operationId: getDeploymentsForRepository
      tags:
      - deployments
      x-tags:
      - tag: deployments
  /repositories/{workspace}/{repo_slug}/commit/{node}/statuses/build:
    post:
      description: |-
        Creates a new build status against the specified commit.

        If the specified key already exists, the existing status object will
        be overwritten.

        When creating a new commit status, you can use a URI template for the URL.
        Templates are URLs that contain variable names that Bitbucket will
        evaluate at runtime whenever the URL is displayed anywhere similar to
        parameter substitution in
        [Bitbucket Connect](https://developer.atlassian.com/bitbucket/concepts/context-parameters.html).
        For example, one could use `https://foo.com/builds/{repository.full_name}`
        which Bitbucket will turn into `https://foo.com/builds/foo/bar` at render time.
        The context variables available are `repository` and `commit`.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: commitstatuses
  /users/{username}/hooks:
    get:
      description: |-
        Returns a paginated list of webhooks installed on this user account.

        Note that the username path parameter has been deprecated due to
        [privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).
        Use the account's UUID or account_id instead.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: webhooks
    post:
      description: |-
        Creates a new webhook on the specified user account.

        Account-level webhooks are fired for events from all repositories
        belonging to that account.

        Note that one can only register webhooks on one's own account, not that
        of others.

        Also, note that the username path parameter has been deprecated due to
        [privacy changes](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis).
        Use the account's UUID or account_id instead.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: webhooks
  /repositories/{workspace}/{repo_slug}/properties/{app_key}/{property_name}:
    delete:
      description: Delete an application property value stored against a repository.
      operationId: deleteRepositoryHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    get:
      description: Retrieve an application property value stored against a repository.
      operationId: getRepositoryHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    put:
      description: Update an application property value stored against a repository.
      operationId: updateRepositoryHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
  /users/{username}/ssh-keys:
    get:
      description: |-
        Returns a paginated list of the user's SSH public keys.

        Example:

        ```
        $ curl https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys
        {
            "page": 1,
            "pagelen": 10,
            "size": 1,
            "values": [
                {
                    "comment": "user@myhost",
                    "created_on": "2018-03-14T13:17:05.196003+00:00",
                    "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY",
                    "label": "",
                    "last_used": "2018-03-20T13:18:05.196003+00:00",
                    "owner": {
                        "display_name": "Mark Adams",
                        "type": "user",
                        "username": "markadams-atl",
                        "nickname": "markadams-atl",
                        "uuid": "{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}"
                    },
                    "type": "ssh_key",
                    "uuid": "{b15b6026-9c02-4626-b4ad-b905f99f763a}"
                }
            ]
        }
        ```
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - ssh
      x-tags:
      - tag: ssh
    post:
      description: |-
        Adds a new SSH public key to the specified user account and returns the resulting key.

        Example:
        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{"key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY user@myhost"}' https://api.bitbucket.org/2.0/users/markadams-atl/ssh-keys

        {
            "comment": "user@myhost",
            "created_on": "2018-03-14T13:17:05.196003+00:00",
            "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqP3Cr632C2dNhhgKVcon4ldUSAeKiku2yP9O9/bDtY",
            "label": "",
            "last_used": "2018-03-20T13:18:05.196003+00:00",
            "owner": {
                "display_name": "Mark Adams",
                "type": "user",
                "username": "markadams-atl",
                "nickname": "markadams-atl",
                "uuid": "{d7dd0e2d-3994-4a50-a9ee-d260b6cefdab}"
            },
            "type": "ssh_key",
            "uuid": "{b15b6026-9c02-4626-b4ad-b905f99f763a}"
        }
        ```
      security:
      - oauth2:
        - account:write
      - basic: []
      - api_key: []
      tags:
      - ssh
      x-tags:
      - tag: ssh
  /snippets/{username}/{encoded_id}/{node_id}:
    delete:
      description: |-
        Deletes the snippet.

        Note that this only works for versioned URLs that point to the latest
        commit of the snippet. Pointing to an older commit results in a 405
        status code.

        To delete a snippet, regardless of whether or not concurrent changes
        are being made to it, use `DELETE /snippets/{encoded_id}` instead.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    get:
      description: |-
        Identical to `GET /snippets/encoded_id`, except that this endpoint
        can be used to retrieve the contents of the snippet as it was at an
        older revision, while `/snippets/encoded_id` always returns the
        snippet's current revision.

        Note that only the snippet's file contents are versioned, not its
        meta data properties like the title.

        Other than that, the two endpoints are identical in behavior.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    put:
      description: |-
        Identical to `UPDATE /snippets/encoded_id`, except that this endpoint
        takes an explicit commit revision. Only the snippet's "HEAD"/"tip"
        (most recent) version can be updated and requests on all other,
        older revisions fail by returning a 405 status.

        Usage of this endpoint over the unrestricted `/snippets/encoded_id`
        could be desired if the caller wants to be sure no concurrent
        modifications have taken place between the moment of the UPDATE
        request and the original GET.

        This can be considered a so-called "Compare And Swap", or CAS
        operation.

        Other than that, the two endpoints are identical in behavior.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat:
    get:
      description: |-
        Redirects to the [repository diffstat](../../diffstat/%7Bspec%7D)
        with the revspec that corresponds to the pull request.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments/{path}:
    delete:
      description: Deletes an attachment.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    get:
      description: |-
        Returns the contents of the specified file attachment.

        Note that this endpoint does not return a JSON response, but instead
        returns a redirect pointing to the actual file that in turn will return
        the raw contents.

        The redirect URL contains a one-time token that has a limited lifetime.
        As a result, the link should not be persisted, stored, or shared.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /users/{username}/pipelines_config/variables/:
    get:
      description: Find user level variables.
      operationId: getPipelineVariablesForUser
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: Create a user level variable.
      operationId: createPipelineVariableForUser
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments:
    get:
      description: |-
        Returns a paginated list of the pull request's comments.

        This includes both global, inline comments and replies.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../../../meta/filtering) for more
        details.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    post:
      description: |-
        Creates a new pull request comment.

        Returns the newly created pull request comment.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /snippets/{username}/{encoded_id}/commits:
    get:
      description: Returns the changes (commits) made on this snippet.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/environments/{environment_uuid}:
    get:
      description: Retrieve an environment
      operationId: getEnvironmentForRepository
      tags:
      - deployments
      x-tags:
      - tag: deployments
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/statuses:
    get:
      description: |-
        Returns all statuses (e.g. build results) for the given pull
        request.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - hasMore: "true"
        tag: pullrequests
      - tag: commitstatuses
  /repositories/{workspace}/{repo_slug}/refs:
    get:
      description: |-
        Returns the branches and tags in the repository.

        By default, results will be in the order the underlying source control system returns them and identical to
        the ordering one sees when running "$ git show-ref". Note that this follows simple
        lexical ordering of the ref names.

        This can be undesirable as it does apply any natural sorting semantics, meaning for instance that refs are
        sorted ["branch1", "branch10", "branch2", "v10", "v11", "v9"] instead of ["branch1", "branch2",
        "branch10", "v9", "v10", "v11"].

        Sorting can be changed using the ?sort= query parameter. When using ?sort=name to explicitly sort on ref name,
        Bitbucket will apply natural sorting and interpret numerical values as numbers instead of strings.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
  /users/{username}:
    get:
      description: |-
        Gets the public information associated with a user account.

        If the user's profile is private, `location`, `website` and
        `created_on` elements are omitted.

        Note that the user object returned by this operation is changing significantly, due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#changes-to-bitbucket-user-objects) for details.
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}:
    get:
      description: Retrieve a specified pipeline
      operationId: getPipelineForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /teams/{username}/hooks/{uid}:
    delete:
      description: |-
        Deletes the specified webhook subscription from the given team
        account.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - hasMore: "true"
        tag: teams
      - tag: webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the given
        team account.
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - hasMore: "true"
        tag: teams
      - tag: webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`
      security:
      - oauth2:
        - webhook
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - hasMore: "true"
        tag: teams
      - tag: webhooks
  /repositories/{workspace}/{repo_slug}/pipelines_config/variables/{variable_uuid}:
    delete:
      description: Delete a repository level variable.
      operationId: deleteRepositoryPipelineVariable
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve a repository level variable.
      operationId: getRepositoryPipelineVariable
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update a repository level variable.
      operationId: updateRepositoryPipelineVariable
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/watchers:
    get:
      description: |-
        Returns a paginated list of all the watchers on the specified
        repository.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/diffstat/{spec}:
    get:
      description: |-
        Returns the diff stat for the specified commit.

        Diff stat responses contain a record for every path modified by the
        commit and lists the number of lines added and removed for each file.


        Example:
        ```
        curl https://api.bitbucket.org/2.0/repositories/bitbucket/geordi/diffstat/d222fa2..e174964
        {
            "pagelen": 500,
            "values": [
                {
                    "type": "diffstat",
                    "status": "modified",
                    "lines_removed": 1,
                    "lines_added": 2,
                    "old": {
                        "path": "setup.py",
                        "type": "commit_file"
                    },
                    "new": {
                        "path": "setup.py",
                        "type": "commit_file"
                    }
                }
            ],
            "page": 1,
            "size": 1
        }
        ```
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /snippets/{username}/{encoded_id}/{revision}/diff:
    get:
      description: |-
        Returns the diff of the specified commit against its first parent.

        Note that this resource is different in functionality from the `patch`
        resource.

        The differences between a diff and a patch are:

        * patches have a commit header with the username, message, etc
        * diffs support the optional `path=foo/bar.py` query param to filter the
          diff to just that one file diff (not supported for patches)
        * for a merge, the diff will show the diff between the merge commit and
          its first parent (identical to how PRs work), while patch returns a
          response containing separate patches for each commit on the second
          parent's ancestry, up to the oldest common ancestor (identical to
          its reachability).

        Note that the character encoding of the contents of the diff is
        unspecified as Git and Mercurial do not track this, making it hard for
        Bitbucket to reliably determine this.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/commit/{node}/comments:
    get:
      description: |-
        Returns the commit's comments.

        This includes both global and inline comments.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
    post:
      description: |-
        Creates new comment on the specified commit.

        To post a reply to an existing comment, include the `parent.id` field:

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/db9ba1e031d07a02603eae0e559a7adc010257fc/comments/ \
          -X POST -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "One more thing!"},
               "parent": {"id": 5728901}}'
        ```
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /users/{username}/properties/{app_key}/{property_name}:
    delete:
      description: Delete an application property value stored against a user.
      operationId: deleteUserHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    get:
      description: Retrieve an application property value stored against a user.
      operationId: retrieveUserHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
    put:
      description: Update an application property value stored against a user.
      operationId: updateUserHostedPropertyValue
      tags:
      - properties
      x-tags:
      - tag: properties
  /addon/linkers:
    get:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /repositories/{workspace}:
    get:
      description: |-
        Returns a paginated list of all repositories owned by the specified
        account or UUID.

        The result can be narrowed down based on the authenticated user's role.

        E.g. with `?role=contributor`, only those repositories that the
        authenticated user has write access to are returned (this includes any
        repo the user is an admin on, as that implies write access).

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../meta/filtering) for more details.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff:
    get:
      description: |-
        Redirects to the [repository diff](../../diff/%7Bspec%7D)
        with the revspec that corresponds to the pull request.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/components:
    get:
      description: |-
        Returns the components that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /snippets:
    get:
      description: |-
        Returns all snippets. Like pull requests, repositories and teams, the
        full set of snippets is defined by what the current user has access to.

        This includes all snippets owned by the current user, but also all snippets
        owned by any of the teams the user is a member of, or snippets by other
        users that the current user is either watching or has collaborated on (for
        instance by commenting on it).

        To limit the set of returned snippets, apply the
        `?role=[owner|contributor|member]` query parameter where the roles are
        defined as follows:

        * `owner`: all snippets owned by the current user
        * `contributor`: all snippets owned by, or watched by the current user
        * `member`: owned by the user, their teams, or watched by the current user

        When no role is specified, all public snippets are returned, as well as all
        privately owned snippets watched or commented on.

        The returned response is a normal paginated JSON list. This endpoint
        only supports `application/json` responses and no
        `multipart/form-data` or `multipart/related`. As a result, it is not
        possible to include the file contents.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    post:
      description: |-
        Creates a new snippet under the authenticated user's account.

        Snippets can contain multiple files. Both text and binary files are
        supported.

        The simplest way to create a new snippet from a local file:

            $ curl -u username:password -X POST https://api.bitbucket.org/2.0/snippets               -F file=@image.png

        Creating snippets through curl has a few limitations and so let's look
        at a more complicated scenario.

        Snippets are created with a multipart POST. Both `multipart/form-data`
        and `multipart/related` are supported. Both allow the creation of
        snippets with both meta data (title, etc), as well as multiple text
        and binary files.

        The main difference is that `multipart/related` can use rich encoding
        for the meta data (currently JSON).


        multipart/related (RFC-2387)
        ----------------------------

        This is the most advanced and efficient way to create a paste.

            POST /2.0/snippets/evzijst HTTP/1.1
            Content-Length: 1188
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "title": "My snippet",
              "is_private": true,
              "scm": "hg",
              "files": {
                  "foo.txt": {},
                  "image.png": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            foo

            --===============1438169132528273974==
            Content-Type: image/png
            MIME-Version: 1.0
            Content-Transfer-Encoding: base64
            Content-ID: "image.png"
            Content-Disposition: attachment; filename="image.png"

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            --===============1438169132528273974==--

        The request contains multiple parts and is structured as follows.

        The first part is the JSON document that describes the snippet's
        properties or meta data. It either has to be the first part, or the
        request's `Content-Type` header must contain the `start` parameter to
        point to it.

        The remaining parts are the files of which there can be zero or more.
        Each file part should contain the `Content-ID` MIME header through
        which the JSON meta data's `files` element addresses it. The value
        should be the name of the file.

        `Content-Disposition` is an optional MIME header. The header's
        optional `filename` parameter can be used to specify the file name
        that Bitbucket should use when writing the file to disk. When present,
        `filename` takes precedence over the value of `Content-ID`.

        When the JSON body omits the `files` element, the remaining parts are
        not ignored. Instead, each file is added to the new snippet as if its
        name was explicitly linked (the use of the `files` elements is
        mandatory for some operations like deleting or renaming files).


        multipart/form-data
        -------------------

        The use of JSON for the snippet's meta data is optional. Meta data can
        also be supplied as regular form fields in a more conventional
        `multipart/form-data` request:

            $ curl -X POST -u credentials https://api.bitbucket.org/2.0/snippets               -F title="My snippet"               -F file=@foo.txt -F file=@image.png

            POST /2.0/snippets HTTP/1.1
            Content-Length: 951
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="image.png"
            Content-Type: application/octet-stream

            ?PNG

            IHDR?1??I.....
            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"

            My snippet
            ------------------------------63a4b224c59f--

        Here the meta data properties are included as flat, top-level form
        fields. The file attachments use the `file` field name. To attach
        multiple files, simply repeat the field.

        The advantage of `multipart/form-data` over `multipart/related` is
        that it can be easier to build clients.

        Essentially all properties are optional, `title` and `files` included.


        Sharing and Visibility
        ----------------------

        Snippets can be either public (visible to anyone on Bitbucket, as well
        as anonymous users), or private (visible only to the owner, creator
        and members of the team in case the snippet is owned by a team). This
        is controlled through the snippet's `is_private` element:

        * **is_private=false** -- everyone, including anonymous users can view
          the snippet
        * **is_private=true** -- only the owner and team members (for team
          snippets) can view it

        To create the snippet under a team account, just append the team name
        to the URL (see `/2.0/snippets/{username}`).
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge:
    post:
      description: Merges the pull request.
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/commit/{node}/statuses:
    get:
      description: Returns all statuses (e.g. build results) for a specific commit.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: commitstatuses
  /users/{username}/repositories:
    get:
      description: |-
        All repositories owned by a user/team. This includes private
        repositories, but filtered down to the ones that the calling user has
        access to.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - hasMore: "true"
        tag: users
      - tag: teams
  /repositories/{workspace}/{repo_slug}/commit/{node}/statuses/build/{key}:
    get:
      description: Returns the specified build status for a commit.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: commitstatuses
    put:
      description: |-
        Used to update the current status of a build status object on the
        specific commit.

        This operation can also be used to change other properties of the
        build status:

        * `state`
        * `name`
        * `description`
        * `url`
        * `refname`

        The `key` cannot be changed.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - hasMore: "true"
        tag: repositories
      - tag: commitstatuses
  /hook_events/{subject_type}:
    get:
      description: |-
        Returns a paginated list of all valid webhook events for the
        specified entity.

        This is public data that does not require any scopes or authentication.

        Example:

        NOTE: The following example is a truncated response object for the `team` `subject_type`.
        We return the same structure for the other `subject_type` objects.

        ```
        $ curl https://api.bitbucket.org/2.0/hook_events/team
        {
            "page": 1,
            "pagelen": 30,
            "size": 21,
            "values": [
                {
                    "category": "Repository",
                    "description": "Whenever a repository push occurs",
                    "event": "repo:push",
                    "label": "Push"
                },
                {
                    "category": "Repository",
                    "description": "Whenever a repository fork occurs",
                    "event": "repo:fork",
                    "label": "Fork"
                },
                ...
                {
                    "category": "Repository",
                    "description": "Whenever a repository import occurs",
                    "event": "repo:imported",
                    "label": "Import"
                }
            ]
        }
        ```
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - webhooks
      x-tags:
      - tag: webhooks
  /user/emails/{email}:
    get:
      description: |-
        Returns details about a specific one of the authenticated user's
        email addresses.

        Details describe whether the address has been confirmed by the user and
        whether it is the user's primary address or not.
      security:
      - oauth2:
        - email
      - basic: []
      - api_key: []
      tags:
      - users
      x-tags:
      - tag: users
  /teams/{username}/members:
    get:
      description: |-
        Returns all members of the specified team. Any member of any of the
        team's groups is considered a member of the team. This includes users
        in groups that may not actually have access to any of the team's
        repositories.

        This operation has been deprecated due to privacy changes.
        See the [announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/)
        for details.
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules/:
    get:
      description: Retrieve the configured schedules for the given repository.
      operationId: getRepositoryPipelineSchedules
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: Create a schedule for the given repository.
      operationId: createRepositoryPipelineSchedule
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /snippets/{username}/{encoded_id}/watch:
    delete:
      description: |-
        Used to stop watching a specific snippet. Returns 204 (No Content)
        to indicate success.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    get:
      description: |-
        Used to check if the current user is watching a specific snippet.

        Returns 204 (No Content) if the user is watching the snippet and 404 if
        not.

        Hitting this endpoint anonymously always returns a 404.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    put:
      description: Used to start watching a specific snippet. Returns 204 (No Content).
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/:
    get:
      description: Find repository level known hosts.
      operationId: getRepositoryPipelineKnownHosts
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: Create a repository level known host.
      operationId: createRepositoryPipelineKnownHost
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/commit/{node}:
    get:
      description: Returns the specified commit.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /repositories/{workspace}/{repo_slug}/src/{node}/{path}:
    get:
      description: |-
        This endpoints is used to retrieve the contents of a single file,
        or the contents of a directory at a specified revision.

        ## Raw file contents

        When `path` points to a file, this endpoint returns the raw contents.
        The response's Content-Type is derived from the filename
        extension (not from the contents). The file contents are not processed
        and no character encoding/recoding is performed and as a result no
        character encoding is included as part of the Content-Type.

        The `Content-Disposition` header will be "attachment" to prevent
        browsers from running executable files.

        If the file is managed by LFS, then a 301 redirect pointing to
        Atlassian's media services platform is returned.

        The response includes an ETag that is based on the contents of the file
        and its attributes. This means that an empty `__init__.py` always
        returns the same ETag, regardless on the directory it lives in, or the
        commit it is on.

        ## File meta data

        When the request for a file path includes the query parameter
        `?format=meta`, instead of returning the file's raw contents, Bitbucket
        instead returns the JSON object describing the file's properties:

        ```javascript
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests/__init__.py?format=meta
        {
          "path": "tests/__init__.py",
          "commit": {
            "type": "commit",
            "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
          },
          "attributes": [],
          "type": "commit_file",
          "size": 0
        }
        ```

        File objects contain an `attributes` element that contains a list of
        possible modifiers. Currently defined values are:

        * `link` -- indicates that the entry is a symbolic link. The contents
            of the file represent the path the link points to.
        * `executable` -- indicates that the file has the executable bit set.
        * `subrepository` -- indicates that the entry points to a submodule or
            subrepo. The contents of the file is the SHA1 of the repository
            pointed to.
        * `binary` -- indicates whether Bitbucket thinks the file is binary.

        This endpoint can provide an alternative to how a HEAD request can be
        used to check for the existence of a file, or a file's size without
        incurring the overhead of receiving its full contents.


        ## Directory listings

        When `path` points to a directory instead of a file, the response is a
        paginated list of directory and file objects in the same order as the
        underlying SCM system would return them.

        For example:

        ```javascript
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/bbql/src/eefd5ef/tests
        {
          "pagelen": 10,
          "values": [
            {
              "path": "tests/test_project",
              "type": "commit_directory",
              "commit": {
                "type": "commit",
                "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
              }
            },
            {
              "path": "tests/__init__.py",
              "commit": {
                "type": "commit",
                "hash": "eefd5ef5d3df01aed629f650959d6706d54cd335"
              },
              "attributes": [],
              "type": "commit_file",
              "size": 0
            }
          ],
          "page": 1,
          "size": 2
        }
        ```

        When listing the contents of the repo's root directory, the use of a
        trailing slash at the end of the URL is required.

        The response by default is not recursive, meaning that only the direct contents of
        a path are returned. The response does not recurse down into
        subdirectories. In order to "walk" the entire directory tree, the
        client can either parse each response and follow the `self` links of each
        `commit_directory` object, or can specify a `max_depth` to recurse to.

        The max_depth parameter will do a breadth-first search to return the contents of the subdirectories
        up to the depth specified. Breadth-first search was chosen as it leads to the least amount of
        file system operations for git. If the `max_depth` parameter is specified to be too
        large, the call will time out and return a 555.

        Each returned object is either a `commit_file`, or a `commit_directory`,
        both of which contain a `path` element. This path is the absolute path
        from the root of the repository. Each object also contains a `commit`
        object which embeds the commit the file is on. Note that this is merely
        the commit that was used in the URL. It is *not* the commit that last
        modified the file.

        Directory objects have 2 representations. Their `self` link returns the
        paginated contents of the directory. The `meta` link on the other hand
        returns the actual `directory` object itself, e.g.:

        ```javascript
        {
          "path": "tests/test_project",
          "type": "commit_directory",
          "commit": { ... }
        }
        ```

        ## Querying, filtering and sorting

        Like most API endpoints, this API supports the Bitbucket
        querying/filtering syntax and so you could filter a directory listing
        to only include entries that match certain criteria. For instance, to
        list all binary files over 1kb use the expression:

        `size > 1024 and attributes = "binary"`

        which after urlencoding yields the query string:

        `?q=size%3E1024+and+attributes%3D%22binary%22`

        To change the ordering of the response, use the `?sort` parameter:

        `.../src/eefd5ef/?sort=-size`

        See [filtering and sorting](../../../../../../meta/filtering) for more
        details.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - source
      x-tags:
      - hasMore: "true"
        tag: source
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/pullrequests/activity:
    get:
      description: |-
        Returns a paginated list of the pull request's activity log.

        This includes comments that were made by the reviewers, updates and
        approvals.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /addon/linkers/{linker_key}/values/:
    delete:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
    get:
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /repositories/{workspace}/{repo_slug}/deploy-keys/{key_id}:
    delete:
      description: |-
        This deletes a deploy key from a repository.

        Example:
        ```
        $ curl -XDELETE \
        -H "Authorization <auth header>" \
        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234
        ```
      security:
      - oauth2:
        - repository
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - deploy
      x-tags:
      - tag: deploy
    get:
      description: |-
        Returns the deploy key belonging to a specific key.

        Example:
        ```
        $ curl -H "Authorization <auth header>" \
        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-key/1234

        Output:
        {
            "comment": "mleu@C02W454JHTD8",
            "last_used": null,
            "repository": {
                "full_name": "mleu/test",
                "name": "test",
                "type": "repository",
                "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
            },
            "label": "mykey",
            "created_on": "2018-08-15T23:50:59.993890+00:00",
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5",
            "id": 1234,
            "type": "deploy_key"
        }
        ```
      security:
      - oauth2:
        - repository
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - deploy
      x-tags:
      - tag: deploy
    put:
      description: |-
        Create a new deploy key in a repository.

        The same key needs to be passed in but the comment and label can change.

        Example:
        ```
        $ curl -XPUT \
        -H "Authorization <auth header>" \
        -H "Content-type: application/json" \
        https://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234 -d \
        '{
            "label": "newlabel",
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5 newcomment"
        }'

        Output:
        {
            "comment": "newcomment",
            "last_used": null,
            "repository": {
                "full_name": "mleu/test",
                "name": "test",
                "type": "repository",
                "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
            },
            "label": "newlabel",
            "created_on": "2018-08-15T23:50:59.993890+00:00",
            "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGbXntEs+BbXiptR+++HycVgl65TMR0b5ul5AgwrVdZdT7qjCOCgaSV74/9xlHDK8oqgGnfA7ZoBBU+qpVyaloSjBdJfLtPY/xqj4yHnXKYzrtn/uFc4Kp9Tb7PUg9Io3qohSTGJGVHnsVblq/rToJG7L5xIo0OxK0SJSQ5vuId93ZuFZrCNMXj8JDHZeSEtjJzpRCBEXHxpOPhAcbm4MzULgkFHhAVgp4JbkrT99/wpvZ7r9AdkTg7HGqL3rlaDrEcWfL7Lu6TnhBdq5",
            "id": 1234,
            "type": "deploy_key"
        }
        ```
      security:
      - oauth2:
        - repository
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - deploy
      x-tags:
      - tag: deploy
  /repositories/{workspace}/{repo_slug}/versions:
    get:
      description: |-
        Returns the versions that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /hook_events:
    get:
      description: |-
        Returns the webhook resource or subject types on which webhooks can
        be registered.

        Each resource/subject type contains an `events` link that returns the
        paginated list of specific events each individual subject type can
        emit.

        This endpoint is publicly accessible and does not require
        authentication or scopes.

        Example:

        ```
        $ curl https://api.bitbucket.org/2.0/hook_events

        {
            "repository": {
            },
            "team": {
            },
            "user": {
            }
        }
        ```
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - webhooks
      x-tags:
      - tag: webhooks
  /repositories/{workspace}/{repo_slug}/components/{component_id}:
    get:
      description: Returns the specified issue tracker component object.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /snippets/{username}/{encoded_id}/commits/{revision}:
    get:
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity:
    get:
      description: |-
        Returns a paginated list of the pull request's activity log.

        This includes comments that were made by the reviewers, updates and
        approvals.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}/executions/:
    get:
      description: Retrieve the executions of a given schedule.
      operationId: getRepositoryPipelineScheduleExecutions
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/watch:
    delete:
      description: Stop watching this issue.
      security:
      - oauth2:
        - issue:write
        - account:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    get:
      description: |-
        Indicated whether or not the authenticated user is watching this
        issue.
      security:
      - oauth2:
        - issue
        - account
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    put:
      description: |-
        Start watching this issue.

        To start watching this issue, do an empty PUT. The 204 status code
        indicates that the operation was successful.
      security:
      - oauth2:
        - issue
        - account:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/commits/{revision}:
    get:
      description: |-
        These are the repository's commits. They are paginated and returned
        in reverse chronological order, similar to the output of `git log` and
        `hg log`. Like these tools, the DAG can be filtered.

        ## GET /repositories/{workspace}/{repo_slug}/commits/

        Returns all commits in the repo in topological order (newest commit
        first). All branches and tags are included (similar to
        `git log --all` and `hg log`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/master

        Returns all commits on rev `master` (similar to `git log master`,
        `hg log master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/dev?exclude=master

        Returns all commits on ref `dev`, except those that are reachable on
        `master` (similar to `git log dev ^master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master

        Returns all commits in the repo that are not on master
        (similar to `git log --all ^master`).

        ## GET /repositories/{workspace}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar

        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or
        `fubar` (similar to `git log foo bar ^fu ^fubar`).

        An optional `path` parameter can be specified that will limit the
        results to commits that affect that path. `path` can either be a file
        or a directory. If a directory is specified, commits are returned that
        have modified any file in the directory tree rooted by `path`. It is
        important to note that if the `path` parameter is specified, the commits
        returned by this endpoint may no longer be a DAG, parent commits that
        do not modify the path will be omitted from the response.

        ## GET /repositories/{workspace}/{repo_slug}/commits/?path=README.md&include=foo&include=bar&exclude=master

        Returns all commits that are on refs `foo` or `bar`, but not on `master`
        that changed the file README.md.

        ## GET /repositories/{workspace}/{repo_slug}/commits/?path=src/&include=foo&include=bar&exclude=master

        Returns all commits that are on refs `foo` or `bar`, but not on `master`
        that changed to a file in any file in the directory src or its children.

        Because the response could include a very large number of commits, it
        is paginated. Follow the 'next' link in the response to navigate to the
        next page of commits. As with other paginated resources, do not
        construct your own links.

        When the include and exclude parameters are more than can fit in a
        query string, clients can use a `x-www-form-urlencoded` POST instead.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
    post:
      description: |-
        Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,
        except that POST allows clients to place the include and exclude
        parameters in the request body to avoid URL length issues.

        **Note that this resource does NOT support new commit creation.**
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - commits
      x-tags:
      - tag: commits
  /repositories/{workspace}/{repo_slug}/pipelines_config/build_number:
    put:
      description: Update the next build number that should be assigned to a pipeline.
        The next build number that will be configured has to be strictly higher than
        the current latest build number for this repository.
      operationId: updateRepositoryBuildNumber
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories/{workspace}/{repo_slug}/branch-restrictions:
    get:
      description: |-
        Returns a paginated list of all branch restrictions on the
        repository.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branchrestrictions
      x-tags:
      - tag: branchrestrictions
    post:
      description: |-
        Creates a new branch restriction rule for a repository.

        `kind` describes what will be restricted. Allowed values include:
        `push`, `force`, `delete` and `restrict_merges`.

        Different kinds of branch restrictions have different requirements:

        * `push` and `restrict_merges` require `users` and `groups` to be
          specified. Empty lists are allowed, in which case permission is
          denied for everybody.
        * `force` can not be specified in a Mercurial repository.

        The restriction applies to all branches that match. There are
        two ways to match a branch. It is configured in `branch_match_kind`:

        1. `glob`: Matches a branch against the `pattern`. A `'*'` in
           `pattern` will expand to match zero or more characters, and every
           other character matches itself. For example, `'foo*'` will match
           `'foo'` and `'foobar'`, but not `'barfoo'`. `'*'` will match all
           branches.
        2. `branching_model`: Matches a branch against the repository's
           branching model. The `branch_type` controls the type of branch
           to match. Allowed values include: `production`, `development`,
           `bugfix`, `release`, `feature` and `hotfix`.

        The combination of `kind` and match must be unique. This means that
        two `glob` restrictions in a repository cannot have the same `kind` and
        `pattern`. Additionally, two `branching_model` restrictions in a
        repository cannot have the same `kind` and `branch_type`.

        `users` and `groups` are lists of users and groups that are except from
        the restriction. They can only be configured in `push` and
        `restrict_merges` restrictions. The `push` restriction stops a user
        pushing to matching branches unless that user is in `users` or is a
        member of a group in `groups`. The `restrict_merges` stops a user
        merging pull requests to matching branches unless that user is in
        `users` or is a member of a group in `groups`. Adding new users or
        groups to an existing restriction should be done via `PUT`.

        Note that branch restrictions with overlapping matchers is allowed,
        but the resulting behavior may be surprising.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - branchrestrictions
      x-tags:
      - tag: branchrestrictions
  /snippets/{username}:
    get:
      description: |-
        Identical to `/snippets`, except that the result is further filtered
        by the snippet owner and only those that are owned by `{username}` are
        returned.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
    post:
      description: |-
        Identical to `/snippets`, except that the new snippet will be
        created under the account specified in the path parameter `{username}`.
      security:
      - oauth2:
        - snippet:write
      - basic: []
      - api_key: []
      tags:
      - snippets
      x-tags:
      - tag: snippets
  /repositories/{workspace}/{repo_slug}/deployments/{deployment_uuid}:
    get:
      description: Retrieve a deployment
      operationId: getDeploymentForRepository
      tags:
      - deployments
      x-tags:
      - tag: deployments
  /repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests:
    get:
      operationId: getPullrequestsForCommit
      summary: Returns a paginated list of all pull requests as part of which this
        commit was reviewed.
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /teams:
    get:
      description: |-
        Returns all the teams that the authenticated user is associated
        with.
      security:
      - oauth2:
        - team
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}:
    delete:
      description: |-
        Deletes the specified issue. This requires write access to the
        repository.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    get:
      description: Returns the specified issue.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    put:
      description: |-
        Modifies the issue.

        ```
        $ curl https://api.bitbucket.org/2.0/repostories/evzijst/dogslow/issues/123 \
          -u evzijst -s -X PUT -H 'Content-Type: application/json' \
          -d '{
          "title": "Updated title",
          "assignee": {
            "username": "evzijst"
          },
          "priority": "minor",
          "version": {
            "name": "1.0"
          },
          "component": null
        }'
        ```

        This example changes the `title`, `assignee`, `priority` and the
        `version`. It also removes the value of the `component` from the issue
        by setting the field to `null`. Any field not present keeps its existing
        value.

        Each time an issue is edited in the UI or through the API, an immutable
        change record is created under the `/issues/123/changes` endpoint. It
        also has a comment associated with the change.
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /teams/{username}:
    get:
      description: |-
        Gets the public information associated with a team.

        If the team's profile is private, `location`, `website` and
        `created_on` elements are omitted.
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch:
    get:
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/issues/export/{repo_name}-issues-{task_id}.zip:
    get:
      description: |-
        This endpoint is used to poll for the progress of an issue export
        job and return the zip file after the job is complete.
        As long as the job is running, this will return a 200 response
        with in the response body a description of the current status.

        After the job has been scheduled, but before it starts executing, this
        endpoint's response is:

        {
         "type": "issue_job_status",
         "status": "ACCEPTED",
         "phase": "Initializing",
         "total": 0,
         "count": 0,
         "pct": 0
        }


        Then once it starts running, it becomes:

        {
         "type": "issue_job_status",
         "status": "STARTED",
         "phase": "Attachments",
         "total": 15,
         "count": 11,
         "pct": 73
        }

        Once the job has successfully completed, it returns a stream of the zip file.
      security:
      - oauth2:
        - repository:admin
        - issue
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /repositories/{workspace}/{repo_slug}/pipelines/:
    get:
      description: Find pipelines
      operationId: getPipelinesForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    post:
      description: "Endpoint to create and initiate a pipeline. \nThere are a couple\
        \ of different options to initiate a pipeline, where the payload of the request\
        \ will determine which type of pipeline will be instantiated.\n# Trigger a\
        \ Pipeline for a branch\nOne way to trigger pipelines is by specifying the\
        \ branch for which you want to trigger a pipeline. \nThe specified branch\
        \ will be used to determine which pipeline definition from the `bitbucket-pipelines.yml`\
        \ file will be applied to initiate the pipeline. The pipeline will then do\
        \ a clone of the repository and checkout the latest revision of the specified\
        \ branch.\n\n### Example\n\n```\n$ curl -X POST -is -u username:password \\\
        \n  -H 'Content-Type: application/json' \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n  -d '\n  {\n    \"target\": {\n      \"ref_type\": \"branch\", \n \
        \     \"type\": \"pipeline_ref_target\", \n      \"ref_name\": \"master\"\n\
        \    }\n  }'\n```\n# Trigger a Pipeline for a commit on a branch or tag\n\
        You can initiate a pipeline for a specific commit and in the context of a\
        \ specified reference (e.g. a branch, tag or bookmark).\nThe specified reference\
        \ will be used to determine which pipeline definition from the bitbucket-pipelines.yml\
        \ file will be applied to initiate the pipeline. The pipeline will clone the\
        \ repository and then do a checkout the specified reference. \n\nThe following\
        \ reference types are supported:\n\n* `branch` \n* `named_branch`\n* `bookmark`\
        \ \n * `tag`\n\n### Example\n\n```\n$ curl -X POST -is -u username:password\
        \ \\\n  -H 'Content-Type: application/json' \\\n  https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n  -d '\n  {\n    \"target\": {\n      \"commit\": {\n        \"type\"\
        : \"commit\", \n        \"hash\": \"ce5b7431602f7cbba007062eeb55225c6e18e956\"\
        \n      }, \n      \"ref_type\": \"branch\", \n      \"type\": \"pipeline_ref_target\"\
        , \n      \"ref_name\": \"master\"\n    }\n  }'\n```\n# Trigger a specific\
        \ pipeline definition for a commit\nYou can trigger a specific pipeline that\
        \ is defined in your `bitbucket-pipelines.yml` file for a specific commit.\
        \ \nIn addition to the commit revision, you specify the type and pattern of\
        \ the selector that identifies the pipeline definition. The resulting pipeline\
        \ will then clone the repository and checkout the specified revision.\n\n\
        ### Example\n\n```\n$ curl -X POST -is -u username:password \\\n  -H 'Content-Type:\
        \ application/json' \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n -d '\n  {\n     \"target\": {\n      \"commit\": {\n         \"hash\"\
        :\"a3c4e02c9a3755eccdc3764e6ea13facdf30f923\",\n         \"type\":\"commit\"\
        \n       },\n        \"selector\": {\n           \"type\":\"custom\",\n  \
        \            \"pattern\":\"Deploy to production\"\n          },\n        \"\
        type\":\"pipeline_commit_target\"\n   }\n  }'\n```\n# Trigger a specific pipeline\
        \ definition for a commit on a branch or tag\nYou can trigger a specific pipeline\
        \ that is defined in your `bitbucket-pipelines.yml` file for a specific commit\
        \ in the context of a specified reference. \nIn addition to the commit revision,\
        \ you specify the type and pattern of the selector that identifies the pipeline\
        \ definition, as well as the reference information. The resulting pipeline\
        \ will then clone the repository a checkout the specified reference.\n\n###\
        \ Example\n\n```\n$ curl -X POST -is -u username:password \\\n  -H 'Content-Type:\
        \ application/json' \\\n https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/\
        \ \\\n -d '\n  {\n     \"target\": {\n      \"commit\": {\n         \"hash\"\
        :\"a3c4e02c9a3755eccdc3764e6ea13facdf30f923\",\n         \"type\":\"commit\"\
        \n       },\n       \"selector\": {\n          \"type\": \"custom\",\n   \
        \       \"pattern\": \"Deploy to production\"\n       },\n       \"type\"\
        : \"pipeline_ref_target\",\n       \"ref_name\": \"master\",\n       \"ref_type\"\
        : \"branch\"\n     }\n  }'\n```\n\n\n# Trigger a custom pipeline with variables\n\
        In addition to triggering a custom pipeline that is defined in your `bitbucket-pipelines.yml`\
        \ file as shown in the examples above, you can specify variables that will\
        \ be available for your build. In the request, provide a list of variables,\
        \ specifying the following for each variable: key, value, and whether it should\
        \ be secured or not (this field is optional and defaults to not secured).\n\
        \n### Example\n\n```\n$ curl -X POST -is -u username:password \\\n  -H 'Content-Type:\
        \ application/json' \\\n https://api.bitbucket.org/2.0/repositories/{workspace}/{repo_slug}/pipelines/\
        \ \\\n -d '\n  {\n    \"target\": {\n      \"type\": \"pipeline_ref_target\"\
        ,\n      \"ref_type\": \"branch\",\n      \"ref_name\": \"master\",\n    \
        \  \"selector\": {\n        \"type\": \"custom\",\n        \"pattern\": \"\
        Deploy to production\"\n      }\n    },\n    \"variables\": [\n      {\n \
        \       \"key\": \"var1key\",\n        \"value\": \"var1value\",\n       \
        \ \"secured\": true\n      },\n      {\n        \"key\": \"var2key\",\n  \
        \      \"value\": \"var2value\"\n      }\n    ]\n  }'\n```\n"
      operationId: createPipelineForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /addon/users/{target_user}/events/{event_key}:
    post:
      description: |-
        POST a new custom event.

        The data within the event body will be hydrated by Bitbucket. For example, the following event
        submission would result in subscribers for the event receiving the full repository object
        corresponding to the UUID.

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "mynumdata": "12345",
            "repository": {
                "type": "repository",
                "uuid": "{be95aa1f-c0b2-47f6-99d1-bf5d3a0f850f}"
        }}' https://api.bitbucket.org/2.0/addon/users/myuser/events/com.example.app%3Amyevent
        ```

        Use the optional `fields` property of the custom event Connect
        module where the event is defined to add additional
        fields to the expanded payload sent to listeners.

        For example, the `customEvents` module in the app descriptor for the previous example would look like this:

        ```
        'modules': {
            'customEvents': {
                'com.example.app:myevent': {
                    'schema': {
                        'properties': {
                            'mynumdata': {'type': 'number'},
                            'repository': {'$ref': '#/definitions/repository'}
                        }
                    },
                    'fields': ['repository.owner']
                }
            }
        }
        ```

        By specifying fields as above, the repository owner
        will also be sent to subscribers of the event.
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - addon
      x-tags:
      - tag: addon
  /repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}:
    delete:
      description: Delete a repository level known host.
      operationId: deleteRepositoryPipelineKnownHost
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve a repository level known host.
      operationId: getRepositoryPipelineKnownHost
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update a repository level known host.
      operationId: updateRepositoryPipelineKnownHost
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /repositories:
    get:
      description: |-
        Returns a paginated list of all public repositories.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../meta/filtering) for more details.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - repositories
      x-tags:
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}:
    delete:
      description: Removes a default reviewer from the repository.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    get:
      description: |-
        Returns the specified reviewer.

        This can be used to test whether a user is among the repository's
        default reviewers list. A 404 indicates that that specified user is not
        a default reviewer.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
    put:
      description: |-
        Adds the specified user to the repository's list of default
        reviewers.

        This method is idempotent. Adding a user a second time has no effect.
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /repositories/{workspace}/{repo_slug}/filehistory/{node}/{path}:
    get:
      description: |-
        Returns a paginated list of commits that modified the specified file.

        Commits are returned in reverse chronological order. This is roughly
        equivalent to the following commands:

            $ git log --follow --date-order <sha> <path>

            $ hg log --follow <path>

        By default, Bitbucket will follow renames and the path name in the
        returned entries reflects that. This can be turned off using the
        `?renames=false` query parameter.

        Results are returned in descending chronological order by default, and
        like most endpoints you can
        [filter and sort](../../../../../../meta/filtering) the response to
        only provide exactly the data you want.

        For example, if you wanted to find commits made before 2011-05-18
        against a file named `README.rst`, but you only wanted the path and
        date, your query would look like this:

        ```
        $ curl 'https://api.bitbucket.org/2.0/repositories/evzijst/dogslow/filehistory/master/README.rst'\
          '?fields=values.next,values.path,values.commit.date&q=commit.date<=2011-05-18'
        {
          "values": [
            {
              "commit": {
                "date": "2011-05-17T07:32:09+00:00"
              },
              "path": "README.rst"
            },
            {
              "commit": {
                "date": "2011-05-16T06:33:28+00:00"
              },
              "path": "README.txt"
            },
            {
              "commit": {
                "date": "2011-05-16T06:15:39+00:00"
              },
              "path": "README.txt"
            }
          ]
        }
        ```

        In the response you can see that the file was renamed to `README.rst`
        by the commit made on 2011-05-16, and was previously named `README.txt`.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - source
      x-tags:
      - hasMore: "true"
        tag: source
      - tag: repositories
  /repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/:
    get:
      description: Find steps for the given pipeline.
      operationId: getPipelineStepsForRepository
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
  /user/permissions/teams:
    get:
      description: "Returns an object for each team the caller is a member of, and\
        \ their\neffective role â\x80\x94 the highest level of privilege the caller\
        \ has. If a\nuser is a member of multiple groups with distinct roles, only\
        \ the\nhighest level is returned.\n\nPermissions can be:\n\n* `admin`\n* `collaborator`\n\
        \nExample:\n\n```\n$ curl https://api.bitbucket.org/2.0/user/permissions/teams\n\
        \n{\n  \"pagelen\": 10,\n  \"values\": [\n    {\n      \"permission\": \"\
        admin\",\n      \"type\": \"team_permission\",\n      \"user\": {\n      \
        \  \"type\": \"user\",\n        \"username\": \"evzijst\",\n        \"nickname\"\
        : \"evzijst\",\n        \"display_name\": \"Erik van Zijst\",\n        \"\
        uuid\": \"{d301aafa-d676-4ee0-88be-962be7417567}\"\n      },\n      \"team\"\
        : {\n        \"username\": \"bitbucket\",\n        \"display_name\": \"Atlassian\
        \ Bitbucket\",\n        \"uuid\": \"{4cc6108a-a241-4db0-96a5-64347ac04f87}\"\
        \n      }\n    }\n  ],\n  \"page\": 1,\n  \"size\": 1\n}\n```\n\nResults may\
        \ be further [filtered or sorted](../../../meta/filtering) by\nteam or permission\
        \ by adding the following query string parameters:\n\n* `q=team.username=\"\
        bitbucket\"` or `q=permission=\"admin\"`\n* `sort=team.display_name`\n\nNote\
        \ that the query parameter values need to be URL escaped so that `=`\nwould\
        \ become `%3D`."
      security:
      - oauth2:
        - account
      - basic: []
      - api_key: []
      tags: []
      x-tags: []
  /snippets/{username}/{encoded_id}/files/{path}:
    get:
      description: |-
        Convenience resource for getting to a snippet's raw files without the
        need for first having to retrieve the snippet itself and having to pull
        out the versioned file links.
      security:
      - oauth2:
        - snippet
      - basic: []
      - api_key: []
      tags:
      - snippet
      x-tags:
      - tag: snippet
  /repositories/{workspace}/{repo_slug}/refs/branches/{name}:
    delete:
      description: |-
        Delete a branch in the specified repository.

        The main branch is not allowed to be deleted and will return a 400
        response.

        For Git, the branch name should not include any prefixes (e.g.
        refs/heads). For Mercurial, this closes all open heads on the branch,
        sets the author of the commit to the authenticated caller, and changes
        the date to the datetime of the call.
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
    get:
      description: |-
        Returns a branch object within the specified repository.

        ```
        $ curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/mercurial/refs/branches/default | jq .
        {
          "heads": [
            {
              "hash": "f1a0933ce59e809f190602655e22ae6ec107c397",
              "type": "commit"
            }
          ],
          "type": "named_branch",
          "name": "default",
          "target": {
            "hash": "f1a0933ce59e809f190602655e22ae6ec107c397",
            "repository": {
              "type": "repository",
              "name": "mercurial",
              "full_name": "seanfarley/mercurial",
              "uuid": "{73dcbd61-e506-4fc1-9ecd-31be2b6d6031}"
            },
            "author": {
              "raw": "Martin von Zweigbergk <martinvonz@google.com>",
              "type": "author",
              "user": {
                "username": "martinvonz",
                "nickname": "martinvonz",
                "display_name": "Martin von Zweigbergk",
                "type": "user",
                "uuid": "{fdb0e657-3ade-4fad-a136-95f1ffe4a5ac}"
              }
            },
            "parents": [
              {
                "hash": "5523aabb85c30ebc2b8e29aadcaf5e13fa92b375",
                "type": "commit"
              }
            ],
            "date": "2018-02-01T18:44:49+00:00",
            "message": "config: replace a for-else by any()",
            "type": "commit"
          }
        }
        ```

        This call requires authentication. Private repositories require the
        caller to authenticate with an account that has appropriate
        authorization.

        For Git, the branch name should not include any prefixes (e.g.
        refs/heads).

        For Mercurial, the response will include an additional field that lists
        the open heads.
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      tags:
      - refs
      x-tags:
      - tag: refs
  /teams/{username}/projects/{project_key}:
    delete:
      security:
      - oauth2:
        - project:write
      - basic: []
      - api_key: []
      tags:
      - projects
      x-tags:
      - tag: projects
    get:
      security:
      - oauth2:
        - project
      - basic: []
      - api_key: []
      tags:
      - projects
      x-tags:
      - tag: projects
    put:
      description: |-
        Since this endpoint can be used to both update and to create a
        project, the request body depends on the intent.

        ### Creation

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The `key` should not be specified in the body of request
        (since it is already present in the URL). The `name` is required,
        everything else is optional.

        ### Update

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The key is not required in the body (since it is already in
        the URL). The key may be specified in the body, if the intent is
        to change the key itself. In such a scenario, the location of the
        project is changed and is returned in the `Location` header of the
        response.
      security:
      - oauth2:
        - project:write
      - basic: []
      - api_key: []
      tags:
      - projects
      x-tags:
      - tag: projects
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments:
    get:
      description: |-
        Returns a paginated list of all comments that were made on the
        specified issue.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../../../meta/filtering) for more details.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
    post:
      description: |-
        Creates a new issue comment.

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/ \
          -X POST -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}}'
        ```
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes/{change_id}:
    get:
      description: |-
        Returns the specified issue change object.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      tags:
      - issue_tracker
      x-tags:
      - tag: issue_tracker
  /pullrequests/{target_user}:
    get:
      description: |-
        Returns all pull requests authored by the specified user.

        By default only open pull requests are returned. This can be controlled
        using the `state` query parameter. To retrieve pull requests that are
        in one of multiple states, repeat the `state` parameter for each
        individual state.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../meta/filtering) for more details.
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /teams/{username}/followers:
    get:
      description: Returns the list of accounts that are following this team.
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      tags:
      - teams
      x-tags:
      - tag: teams
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline:
    post:
      description: Declines the pull request.
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      tags:
      - pullrequests
      x-tags:
      - tag: pullrequests
  /users/{username}/pipelines_config/variables/{variable_uuid}:
    delete:
      description: Delete an account level variable.
      operationId: deletePipelineVariableForUser
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    get:
      description: Retrieve a user level variable.
      operationId: getPipelineVariableForUser
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
    put:
      description: Update a user level variable.
      operationId: updatePipelineVariableForUser
      tags:
      - pipelines
      x-tags:
      - tag: pipelines
components:
  securitySchemes:
    api_key:
      description: API Keys can be used as Basic HTTP Authentication credentials and
        provide a substitute for the account's actual username and password. API Keys
        are only available to team accounts and there is only 1 key per account. API
        Keys do not support scopes and have therefore access to all contents of the
        account.
      in: header
      name: Authorization
      type: apiKey
    basic:
      description: Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617)
        (Digest not supported). Note that Basic Auth with username and password as
        credentials is only available on accounts that have 2-factor-auth / 2-step-verification
        disabled. If you use 2fa, you should authenticate using OAuth2 instead.
      scheme: basic
      type: http
    oauth2:
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
[...]
