# Catalog Info Template
# Place this file at the root of your repository as catalog-info.yaml

apiVersion: astrabit.io/v1
kind: Component
metadata:
  # Required: Unique identifier for this component
  name: service-name

  # Optional: Human-readable description
  description: Brief description of what this service does

  # Optional: Tags for discovery and grouping
  tags:
    - backend
    - microservice

spec:
  # --- Service Classification ---

  # Required: Type of component
  # Options: service, gateway, worker, library, frontend, database
  type: service

  # Optional: Broader category
  category: backend

  # Optional: Business domain
  domain: trading

  # Optional: Team responsible for this component
  owner: platform-team

  # Optional: Lifecycle stage
  lifecycle: production  # experimental, production, deprecated

  # --- Dependencies ---

  # Upstream dependencies (services, databases, etc.)
  dependsOn:
    - component: auth-service
      type: service
    - component: user-db
      type: database
    - component: redis-cache
      type: cache

  # --- APIs ---

  # APIs provided by this component
  providesApis:
    - name: User API
      type: REST
      definition: ./openapi.yaml

  # APIs consumed by this component
  consumesApis:
    - name: Auth API
      providedBy: auth-service

  # --- Events ---

  # Events produced by this component
  eventProducers:
    - name: user-events
      type: kafka
      topic: user.created
      schema: avro
    - name: user-events
      type: kafka
      topic: user.updated
      schema: avro

  # Events consumed by this component
  eventConsumers:
    - name: order-events
      type: kafka
      topic: order.placed
      group: user-service-group

  # --- HTTP Routes (for gateways and services) ---

  routes:
    - path: /api/users/*
      methods: [GET, POST, PUT, DELETE]
      handler: this
    - path: /api/auth/*
      methods: [POST]
      forwardsTo: auth-service

  # --- Infrastructure ---

  # Runtime technology
  runtime: nodejs  # nodejs, python, go, java, rust, etc.

  # Framework used
  framework: nestjs  # nestjs, fastapi, spring, echo, etc.
