name: Download Skillstore CLI
description: Download and setup skillstore-cli binary

inputs:
  version:
    description: 'CLI version (default: latest)'
    required: false
    default: 'latest'
  token:
    description: 'GitHub token with repo access'
    required: true

outputs:
  cli-path:
    description: 'Path to the CLI binary'
    value: ${{ github.workspace }}/skillstore-cli

runs:
  using: composite
  steps:
    - name: Resolve CLI version
      id: resolve
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        CLI_VERSION: ${{ inputs.version }}
        CLI_REPO: aiskillstore/skillstore
      run: |
        if [ "$CLI_VERSION" = "latest" ]; then
          echo "Fetching latest release tag..."
          RELEASE_TAG=$(gh release view --repo "$CLI_REPO" --json tagName -q '.tagName')
          echo "Latest release: $RELEASE_TAG"
        else
          RELEASE_TAG="cli-v$CLI_VERSION"
          echo "Using specified version: $RELEASE_TAG"
        fi
        echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

    - name: Download CLI
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        CLI_REPO: aiskillstore/skillstore
        RELEASE_TAG: ${{ steps.resolve.outputs.release-tag }}
      run: |
        echo "Downloading skillstore-cli ($RELEASE_TAG)..."

        gh release download "$RELEASE_TAG" \
          --repo "$CLI_REPO" \
          --pattern "skillstore-cli-linux-x64" \
          --output "$GITHUB_WORKSPACE/skillstore-cli" \
          --clobber

        chmod +x "$GITHUB_WORKSPACE/skillstore-cli"

    - name: Verify CLI
      shell: bash
      run: |
        CLI_PATH="$GITHUB_WORKSPACE/skillstore-cli"

        if [ ! -f "$CLI_PATH" ]; then
          echo "❌ CLI not found at $CLI_PATH"
          exit 1
        fi

        echo "✅ CLI downloaded successfully"
        echo "CLI path: $CLI_PATH"
        echo "CLI version:"
        "$CLI_PATH" --version
