version: 1.0
project_name: "Demo Project"
steps:
  - step_id: "001"
    timestamp: "2026-01-04T10:00:00"
    intent: "Scaffold Project"
    prompt: "Create a basic Python web server using Flask."
    output_files: ["app.py", "requirements.txt"]
    git_sha: "a1b2c3d"

  - step_id: "002"
    timestamp: "2026-01-04T10:15:00"
    intent: "Add Authentication"
    prompt: "Add a login route that returns a JWT."
    output_files: ["app.py", "auth.py"]
    git_sha: "e5f6g7h"
