# ABOUTME: Defines the structure for worldview data - ideas, sources, and relationships
# ABOUTME: Used to validate and organize the knowledge graph

# An Idea is a discrete belief, concept, or claim
Idea:
  id: string           # unique slug (e.g., "consciousness-is-fundamental")
  title: string        # human-readable name
  domain: enum         # metaphysics | epistemology | ethics | society | technology | personal
  claim: string        # the actual belief/claim in one sentence
  confidence: float    # 0.0 to 1.0 - how certain you are
  importance: float    # 0.0 to 1.0 - how central to your worldview
  tags: list[string]   # flexible categorization
  sources: list[string]  # ids of Source objects that inform this
  supports: list[string] # ids of Ideas this one supports/implies
  tensions: list[string] # ids of Ideas this one is in tension with
  notes: string        # optional elaboration

# A Source is an external influence (URL, book, person, experience)
Source:
  id: string           # unique slug
  type: enum           # url | book | video | podcast | person | experience
  title: string        # name/title
  url: string          # if applicable
  author: string       # if applicable
  summary: string      # what you took from it
  extracted_ideas: list[string]  # ideas derived from this source
  date_added: date
  influence: float     # 0.0 to 1.0 - how much this shaped you

# A Tension is an unresolved conflict between ideas
Tension:
  id: string
  ideas: list[string]  # the 2+ ideas in conflict
  description: string  # what the tension is
  resolution: string   # optional - how you resolve it (if you do)
  status: enum         # unresolved | resolved | embraced (as productive paradox)
